### ISSUE TITLE
Building container images from within Mock(chroot) does not work

### ISSUE THREAD

**Issue by ignatenkobrain** [OSInside/kiwi#2020] opened 2022-01-09 11:48 UTC
## Problem description

As part of the Koji adoption, I've been trying also to build container images, but that did not go smooth.

```
DEBUG util.py:444:  [ ERROR   ]: 01:31:29 | KiwiCommandError: buildah: stderr: Getting image source signatures
DEBUG util.py:444:  Copying blob sha256:27c3f988a847f29d7b93105f07994c4cc9d73b304047aadc98b628d2c7b3948f
DEBUG util.py:444:  error committing container "kiwi-container-hwwgr4" to "kiwi-image-8hwgf6:tag-o35idx": error copying layers and metadata for container "d44cd072c57ee0b0685995b7e39bdd29681fd5bf2c8481450fbdd994cc642ed7": writing blob: adding layer with blob "sha256:27c3f988a847f29d7b93105f07994c4cc9d73b304047aadc98b628d2c7b3948f": Error processing tar file(exit status 1): remount /, flags: 0x44000: invalid argument
DEBUG util.py:444:  , stdout: (no output on stdout)
DEBUG util.py:444:  Exception ignored in: <function OCIBuildah.__del__ at 0x7fecbb9d74c0>
DEBUG util.py:444:  Traceback (most recent call last):
DEBUG util.py:444:    File "/usr/lib/python3.9/site-packages/kiwi/oci_tools/buildah.py", line 327, in __del__
DEBUG util.py:444:      Command.run(['buildah', 'rmi', self.working_image])
DEBUG util.py:444:    File "/usr/lib/python3.9/site-packages/kiwi/command.py", line 133, in run
DEBUG util.py:444:      raise KiwiCommandError(
DEBUG util.py:444:  kiwi.exceptions.KiwiCommandError: buildah: stderr: 1 error occurred:
DEBUG util.py:444:  	* kiwi-image-8hwgf6:tag-o35idx: image not known
DEBUG util.py:444:  , stdout: (no output on stdout)
DEBUG util.py:598:  Child return code was: 1
```

## Expected behaviour

Build works.

## Steps to reproduce the behaviour

Build some simple container image (of CentOS Stream 9) within `mock` (which will setup chroot) on CentOS Stream 8.

## OS and Software information
+ KIWI version: 9.24.15
+ Operating system: CentOS Stream 8 (host), CentOS Stream 9 (target, in chroot)
+ OBS version: N/A

**Comment by ignatenkobrain** [comment] 2022-01-09 11:58
As mentioned in the description, I don't think this is purely kiwi issue but more like of the environment where it is executed… However I think something either can be done from kiwi side (is https://github.com/containers/buildah/issues/2554#issuecomment-938494919 of any help?) or we can possibly track some work here on adjusting koji to do something to fix this issue?

**Comment by schaefi** [comment] 2022-01-09 18:58
I must admit I haven't done much with buildah (mostly on umoci/skopeo)

I hope @davidcassany has an idea.

**Comment by schaefi** [comment] 2022-03-07 09:51
Unfortunately there was no response to this topic so far. I also realized we have buildah support implemented but no integration test build for it, which is bad. I will bring up this topic at the community meeting. We have a resource problem here as I will not have time to look into more issues and it seems David has also only limited time to look into it.

**Comment by davidcassany** [comment] 2022-03-08 11:20
I think we can explore using the `--isolation chroot` in KIWI builds using buildah, in fact, this looks like a better option from KIWI PoV as KIWI itself is based on chroot and not on container technologies. However I think this only works around runc usage, not the container storage, which seams to be the issue at a glance as it seams to fail while committing layers to storage.

@ignatenkobrain if you can help me with the reproducer I'll be happy to spend some cycles exploring few buildah options that might be better suited for KIWI build process, like chroot isolation instead of runc envs.

I never used `mock` before (can it be easily installed from a package?), so if anyone can give me a quick start for dummies or step by step reproducer of this issue I would be very happy.

**Comment by schaefi** [comment] 2022-03-08 17:08
For reference the relevant part in Mock:
* https://github.com/rpm-software-management/mock/blob/main/mock/py/mockbuild/buildroot.py#L161-L255

**Comment by schaefi** [comment] 2022-03-13 19:39
As promised from the community meeting I have created an integration test to build a docker image with buildah. You can find the test build here:

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:fedora/test-image-docker

The build succeeds and I can use the created container as expected. The relevant buildah commands summarizes in the log to

```
osc buildlog images x86_64 | grep buildah

[  106s] [545/587] installing buildah-1.20.0-1.fc34
[  122s] [ DEBUG   ]: 16:47:50 | EXEC: [buildah --version]
[  154s] [ DEBUG   ]: 16:48:22 | EXEC: [buildah from --name kiwi-container-vx5k1z scratch]
[  155s] [ DEBUG   ]: 16:48:23 | EXEC: [buildah mount kiwi-container-vx5k1z]
[  163s] [ DEBUG   ]: 16:48:31 | EXEC: [buildah umount kiwi-container-vx5k1z]
[  163s] [ WARNING ]: 16:48:31 | Author field in history is ignored using buildah
[  163s] [ DEBUG   ]: 16:48:31 | EXEC: [buildah config --author=Marcus Schäfer <marcus.schaefer@gmail.com> --cmd=/bin/bash --label=org.openbuildservice.disturl=obs://build.opensuse.org/Virtualization:Appliances:Images:Testing_x86:fedora/images/74a700193bbcac66a9ce719d7eb7a720-test-image-docker --created-by=KIWI 9.24.29 kiwi-container-vx5k1z]
[  163s] [ DEBUG   ]: 16:48:31 | EXEC: [buildah commit --rm --format oci kiwi-container-vx5k1z kiwi-image-n6md5h:tag-kcxkuh]
[  250s] [ DEBUG   ]: 16:49:58 | EXEC: [buildah rmi e838084fed1ecf4c52b9dad7798b8bcd9cb44b353ec1f02018476a2909934744]

```

As base for the test the Fedora34 distro was used. The caller environment is Fedora34 as the buildservice sets this up prior calling kiwi inside of it.

From my perspective the test shows that the implementation in kiwi regarding the use of buildah is correct. However, it seems that the Mock created environment is not suitable to run container build processes in the way buildah expects it ?

I didn't took a look into Mock and I also don't have time to do it. It looks like @davidcassany was right with his assumptions about the environment.

@ignatenkobrain it would be great if you can take this information as base for a conversation on the Mock side of things ? Do you think this would be possible ?

Unless there are objections I'm closing this issue on behalf of our findings by the end of next week.

Thanks

**Comment by ignatenkobrain** [comment] 2022-04-06 11:22
Oh, I did not notice the comments.

This is still the issue and I can provide simple reproducer next week(end).

**Comment by ignatenkobrain** [comment] 2022-04-16 06:55
(config.kiwi is the almost exact copy of https://build.opensuse.org/package/view_file/Virtualization:Appliances:Images:Testing_x86:fedora/test-image-docker/_service:obs_scm:appliance.kiwi?expand=1)

Only repositories are used:

```xml
    <repository type="rpm-md" sourcetype="metalink">
        <source path="https://mirrors.fedoraproject.org/metalink?repo=fedora-36&amp;arch=$basearch&amp;protocol=https"/>
    </repository>
```

Simplest reproducer:

```sh
mock -r fedora-36-x86_64 --init
mock -r fedora-36-x86_64 --install kiwi-cli kiwi-systemdeps
mock -r fedora-36-x86_64 --copyin ./config.kiwi /builddir/build/
mock -r fedora-36-x86_64 --isolation simple --enable-network --shell
cd build
kiwi-ng system build --description . --target-dir kiwi-result
```

gives:

```
Getting image source signatures
Copying blob sha256:d8c7f4dad1e99464d879c4c1360b3be6a65982ebf8d6b6c14e1a766a071982a4
error committing container "kiwi-container-eait2h" to "kiwi-image-bdfo1q:tag-8l6t3t": error copying layers and metadata for container "9a4020f0a460e014bc18d64078d05fd01bdf6ddc2543a0c5a682f874f22d3987": writing blob: adding layer with blob "sha256:d8c7f4dad1e99464d879c4c1360b3be6a65982ebf8d6b6c14e1a766a071982a4": Error processing tar file(exit status 1): remount /, flags: 0x44000: invalid argument
, stdout: (no output on stdout)
Exception ignored in: <function OCIBuildah.__del__ at 0x7f3a180dfa30>
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/kiwi/oci_tools/buildah.py", line 331, in __del__
    Command.run(['buildah', 'rmi', self.working_image])
  File "/usr/lib/python3.10/site-packages/kiwi/command.py", line 133, in run
    raise KiwiCommandError(
kiwi.exceptions.KiwiCommandError: buildah: stderr: 1 error occurred:
	* kiwi-image-bdfo1q:tag-8l6t3t: image not known
```

**Comment by davidcassany** [comment] 2022-07-12 10:21
Finally I managed to spend some time having a look to this issue. I managed to reproduce this same issue in a Fedora host building openSUSE or Fedora images, in both cases the issue turns to be the same. I did quite few trials with different `/etc/containers/containers.conf` values and I always ended up with the same error as reported here. See the logs:

```
[ DEBUG   ]: 15:47:17 | EXEC: [buildah config --author=Marcus Schaefer <ms@suse.de> --cmd=/bin/bash --created-by=KIWI 9.24.17 kiwi-container-hwyff9]
[ DEBUG   ]: 15:47:17 | EXEC: [buildah commit --rm --format oci kiwi-container-hwyff9 kiwi-image-bw1ogm:tag-xf32pa]
[ DEBUG   ]: 15:47:39 | EXEC: Failed with stderr: Getting image source signatures
Copying blob sha256:7575e864f3d0380f7e92b3c14a0439ab60b48ca5a4bf6eebbd8f6cfdf7c81448
error committing container "kiwi-container-hwyff9" to "kiwi-image-bw1ogm:tag-xf32pa": error copying layers and metadata for container "c6479e35fe0f55ebab4b1d3e715ccdb277599a35aa74aa1e2b1001d67e2332f8": writing blob: adding layer with blob "sha256:7575e864f3d0380f7e92b3c14a0439ab60b48ca5a4bf6eebbd8f6cfdf7c81448": Error processing tar file(exit status 1): remount /, flags: 0x44000: invalid argument
, stdout: (no output on stdout)
```

Did some googling with the error message and only issues I found (https://github.com/containers/podman/issues/8903 and https://github.com/containers/buildah/issues/2554) that were relatively close were pointing to some missing capabilities within within the execution environment or some odd chroot setup. Up to my tests the chroot already includes all capabilities and I could not see anything from mock limiting capabilities in the chrooted environment. I also tested by manually preparing and mounting the chroot and I ended up with the same exact result. Feels like it is missing some chroot detail to properly work as the mentioned issues seams to have managed it in some way or another.

**Closed** 2022-10-22 20:11 UTC

**Comment by Vogtinator** [comment] 2024-08-22 12:32
> Did some googling with the error message and only issues I found (https://github.com/containers/podman/issues/8903 and https://github.com/containers/buildah/issues/2554) that were relatively close were pointing to some missing capabilities within within the execution environment or some odd chroot setup. Up to my tests the chroot already includes all capabilities and I could not see anything from mock limiting capabilities in the chrooted environment. I also tested by manually preparing and mounting the chroot and I ended up with the same exact result. Feels like it is missing some chroot detail to properly work as the mentioned issues seams to have managed it in some way or another.

`remount /, flags: 0x44000: invalid argument` happens if `/` is not a mount point. Simple solution:

`mount --bind / /`
