### ISSUE TITLE
efiparttable="msdos" breaks on Tumbleweed

### ISSUE THREAD

**Issue by ggardet** [OSInside/kiwi#1749] opened 2021-03-03 16:16 UTC
## Problem description
`JeOS-zturn.kiwi` fails in Tumbleweed because of ` efiparttable="msdos"`

Log:
```
[  269s] [ INFO    ]: 14:40:28 | Creating system image
[  269s] [ DEBUG   ]: 14:40:28 | EXEC: [chroot /usr/src/packages/KIWI-oem/build/image-root dracut --list-modules --no-kernel]
[  269s] [ DEBUG   ]: 14:40:29 | EXEC: [chroot /usr/src/packages/KIWI-oem/build/image-root dracut --list-modules --no-kernel]
[  269s] [ DEBUG   ]: 14:40:29 | EXEC: [bash -c rm -f /usr/src/packages/KIWI-oem/build/image-root/recovery.*]
[  269s] [ INFO    ]: 14:40:29 | Preparing boot system
[  269s] [ INFO    ]: 14:40:29 | Precalculating required disk size
[  269s] [ DEBUG   ]: 14:40:29 | EXEC: [du -s --apparent-size --block-size 1 --exclude /usr/src/packages/KIWI-oem/build/image-root/proc --exclude /usr/src/packages/KIWI-oem/build/image-root/sys --exclude /usr/src/packages/KIWI-oem/build/image-root/dev /usr/src/packages/KIWI-oem/build/image-root]
[  270s] [ DEBUG   ]: 14:40:30 | EXEC: [bash -c find /usr/src/packages/KIWI-oem/build/image-root | wc -l]
[  271s] [ INFO    ]: 14:40:31 | --> system data with filesystem overhead needs 1526 MB
[  271s] [ INFO    ]: 14:40:31 | --> swap partition adding 500 MB
[  271s] [ INFO    ]: 14:40:31 | --> EFI partition adding 16 MB
[  271s] [ INFO    ]: 14:40:31 | Using calculated disk size: 2042 MB
[  271s] [ INFO    ]: 14:40:31 | Creating raw disk image /usr/src/packages/KIWI-oem/openSUSE-Tumbleweed-ARM-JeOS-zturn.armv7l-2021.02.24.raw
[  271s] [ DEBUG   ]: 14:40:31 | EXEC: [qemu-img create /usr/src/packages/KIWI-oem/openSUSE-Tumbleweed-ARM-JeOS-zturn.armv7l-2021.02.24.raw 2042M]
[  271s] [ DEBUG   ]: 14:40:31 | EXEC: [losetup -f --show /usr/src/packages/KIWI-oem/openSUSE-Tumbleweed-ARM-JeOS-zturn.armv7l-2021.02.24.raw]
[  271s] [ DEBUG   ]: 14:40:31 | Initialize msdos disk
[  271s] [ DEBUG   ]: 14:40:31 | EXEC: [sgdisk --zap-all /dev/loop0]
[  272s] [ INFO    ]: 14:40:32 | --> creating EFI partition
[  272s] [ DEBUG   ]: 14:40:32 | p.UEFI: fdisk: n p 1 cur_position +16M w q
[  272s] [ DEBUG   ]: 14:40:32 | EXEC: [bash -c cat /tmp/tmpzn6b0m5b | fdisk /dev/loop0]
[  272s] [ DEBUG   ]: 14:40:32 | EXEC: Failed with stderr: Re-reading the partition table failed.: Invalid argument
[  272s] , stdout: 
[  272s] Welcome to fdisk (util-linux 2.36.2).
[  272s] Changes will remain in memory only, until you decide to write them.
[  272s] Be careful before using the write command.
[  272s] 
[  272s] Device does not contain a recognized partition table.
[  272s] Created a new DOS disklabel with disk identifier 0xc9aaa82a.
[  272s] 
[  272s] Command (m for help): Partition type
[  272s]    p   primary (0 primary, 0 extended, 4 free)
[  272s]    e   extended (container for logical partitions)
[  272s] Select (default p): Partition number (1-4, default 1): First sector (2048-4182015, default 2048): Last sector, +/-sectors or +/-size{K,M,G,T,P} (8192-4182015, default 4182015): 
[  272s] Created a new partition 1 of type 'Linux' and of size 16 MiB.
[  272s] 
[  272s] Command (m for help): The partition table has been altered.
[  272s] Calling ioctl() to re-read partition table.
[  272s] 
[  272s] The kernel still uses the old table. The new table will be used at the next reboot or after you run partprobe(8) or partx(8).
[  272s] 
[  272s] 
[  272s] [ DEBUG   ]: 14:40:32 | potential fdisk errors were ignored
[  272s] [ WARNING ]: 14:40:32 | Flag t.efi ignored on msdos
[  272s] [ INFO    ]: 14:40:32 | --> creating SWAP partition
[  272s] [ DEBUG   ]: 14:40:32 | p.swap: fdisk: n p 2 cur_position +500M w q
[  272s] [ DEBUG   ]: 14:40:32 | EXEC: [bash -c cat /tmp/tmpv8y344td | fdisk /dev/loop0]
[  272s] [ DEBUG   ]: 14:40:32 | EXEC: [sfdisk -c /dev/loop0 2 82]
[  272s] [ DEBUG   ]: 14:40:32 | EXEC: Failed with stderr: sfdisk: --id is deprecated in favour of --part-type
[  272s] sfdisk: /dev/loop0: partition 2: partition is unused
[  272s] , stdout: (no output on stdout)
[  272s] [ ERROR   ]: 14:40:32 | KiwiCommandError: sfdisk: stderr: sfdisk: --id is deprecated in favour of --part-type
[  272s] sfdisk: /dev/loop0: partition 2: partition is unused
[  272s] , stdout: (no output on stdout)
[  272s] [ INFO    ]: 14:40:32 | Cleaning up LoopDevice instance
[  272s] [ DEBUG   ]: 14:40:32 | EXEC: [losetup -d /dev/loop0]
[  272s] [ INFO    ]: 14:40:32 | Cleaning up BootLoaderConfigGrub2 instance
```

It started to fail on 02/02/2021. Which seems to match the update from 9.22.1 to 9.23.5: https://build.opensuse.org/request/show/863255

## Expected behaviour
It should build properly.

## Steps to reproduce the behaviour
Check kiwi file on OBS: https://build.opensuse.org/package/view_file/openSUSE:Factory:ARM/JeOS/JeOS-zturn.kiwi?expand=1

## OS and Software information
+ KIWI version: 9.23.16
+ Operating system: openSUSE Tumbleweed  armv7
+ OBS version: build.o.o

**Comment by schaefi** [comment] 2021-03-05 10:14
please don't tell me that sfdisk broke their user interface in an incompatible way. ```sfdisk -c /dev/loop0 2 82``` This has worked for decades and I bet if we adapt it to work in TW it will fail for older versions. Not nice

**Comment by schaefi** [comment] 2021-03-05 10:15
Or is this just an after effect of ```sfdisk: /dev/loop0: partition 2: partition is unused``` ? pretty confusing

**Comment by Conan-Kudo** [comment] 2021-03-11 13:38
@schaefi `sfdisk` has a `--json` output mode that we probably should be using...

**Comment by schaefi** [comment] 2021-04-11 19:32
> I've failed to reproduce it on TW. The deprecation warning itself doesn't lead to error exit code. The issue is in "partition is unused"

I agree and I have no idea what causes it in this particular case. @ggardet I'm lost with this one to be honest.

**Comment by matwey** [comment] 2021-04-15 07:04
I've tried to run the build as `osc build --clean --local images armv7l JeOS-zturn.kiwi`, but no luck: it fails in the different place.

**Comment by matwey** [comment] 2021-04-19 16:24
Just reproduced it in osc:

```
osc build --nopreinstallimage --clean --local images armv7l JeOS-zturn.kiwi
```

**Comment by matwey** [comment] 2021-04-19 16:52
So, there is only one partition in the image:

```
Device       Boot Start   End Sectors Size Id Type
/dev/loop0p1       8192 40959   32768  16M 83 Linux
```

That is why `sfdisk` complaining.

**Comment by matwey** [comment] 2021-04-19 16:56
fdisk doesn't want to understand `+500M`:

```
# fdisk /dev/loop0

Welcome to fdisk (util-linux 2.36.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): n
Partition type
   p   primary (1 primary, 0 extended, 3 free)
   e   extended (container for logical partitions)
Select (default p): p
Partition number (2-4, default 2): 2
First sector (2048-4095999, default 2048):
Last sector, +/-sectors or +/-size{K,M,G,T,P} (2048-8191, default 8191): +500M
Value out of range.
```

**Comment by matwey** [comment] 2021-04-19 17:21
I think that the reason is that the msdos partitioner doesn't behave well with `disk_start_sector="8192"`.
This option has been introduced recently for all boards as a default.

**Comment by schaefi** [comment] 2021-05-11 09:03
I was able to reproduce this issue on all architectures for which fdisk can be used, also on x86. As soon as you set

```
disk_start_sector="8192"
```

you run into the issue @matwey found: 

```
Last sector, +/-sectors or +/-size{K,M,G,T,P} (2048-8191, default 8191): +500M
Value out of range.
```

If I delete the start sector setting the image build completes. I also tried with reducing the +500M to a smaller value but it always fails. From my perspective this is an issue with fdisk which we can't fix in kiwi

**Comment by schaefi** [comment] 2021-05-11 10:35
I think it's the job of a partitioner tool to know about the start sector of a subsequent partition. The start sector of the very first partition can vary depending on the later target hardware and might be a setting that needs to be done. This is probably the
reason why disk_start_sector was set here instead of using the partitioners default. Any subsequent partition in the table should
not leave gaps and should properly align. Especially the later is something the partitioner tools implements their own understanding and is often in conflict of self calculated sector values. In addition CHS calculation is from times when we had real magnetic drives and nothing else than 512byte block storage. When we create images with the 4k blocksize and the loop setup as such it could also cause negative side effects if kiwi does the job of the partitioner tool :)

In past kiwi code we thought all tables can be generated using parted and we let kiwi calculate the geometry itself. We ended up in a nightmare of side effects for the different tables types: DOS, GPT, DASD, FCP ... and their architectures. In an effort of refactoring this was changed to use the "standard" partitioning tool according to table type and architecture and the expectation was set that partitions can be created with this tool with respect to its individual features.

If we use fdisk and start the partition table with anything different than fdisk's default setting it will lead to the issue described here. I agree with you it could be circumvented by kiwi calculating the "correct" start sector for any subsequent partition but we won't change kiwi for this. I think if fdisk works correctly with disk_start_sector="2048" it should also work correctly with disk_start_sector="something-different" and if it doesn't it imho deserves a fix in fdisk. I'm sure fdisk has code to deal with the start sector and it might be relatively simple to make it work there instead of opening a can of worms in kiwi which we had before and are not eager to get back.

I hope this makes some sort of sense for you too

**Comment by matwey** [comment] 2021-05-11 12:08
I would like to note that we use DOS partition table for some ARM boards due to its bootrom restrictions. For instance, Xilinx Zynq SoC is looking for bootloader at first DOS partition, or Amlogic S902x looking for bootloader at the sector next to MBR, so GPT cannot be placed there.

At the same time `disk_start_sector` was introduced for the purpose to allow more space for a bootloader image when it is located before the first partition. So, for particular JeOS-zturn board we can just safely discard using `disk_start_sector`. But this issue will rise again eventually for some other board.

**Comment by matwey** [comment] 2021-05-11 12:09
Can we use something instead `fdisk` to prepare DOS partition table in kiwi?

**Comment by ggardet** [comment] 2021-05-12 07:15
As a workaround, I disabled `disk_start_sector` setting for  `JeOS-zturn` in https://build.opensuse.org/request/show/892375
We can revert once it is fixed.

**Comment by schaefi** [comment] 2021-05-12 07:56
> Can we use something instead `fdisk` to prepare DOS partition table in kiwi?

Do you have a better candidate in mind ? I'm open to switch tools to the solution that works best :)

**Comment by matwey** [comment] 2021-05-12 09:55
I don't have any good ideas. But whats about reusing https://github.com/openSUSE/libstorage-ng ?

**Comment by schaefi** [comment] 2021-05-12 10:12
To my knowledge libstorage-ng is not widely adopted. It finds its way into yast and does not exist in the core of other distributions. With kiwi we need a solution that works on a generic level since we support suse,sles,rhel,fedora,debian,ubuntu,arch... more to come. Thus the partitioner interface is implemented in a way that uses tools available everywhere. So far we could avoid to self provide packages for all supported distros, the last time we did that it was with hwinfo ... and to be honest I was quite happy when it was gone.

libstorage comes as a library. On a short look I could not see if it has a stable python interface, which would be a requirement for kiwi if there is no standalone tool around. https://pypi.org/search/?q=libstorage doesn't list a version of it

**Comment by Conan-Kudo** [comment] 2021-05-12 10:28
Another option is [`pyparted`](https://pypi.org/project/pyparted/), which is available everywhere but openSUSE (which is an easy problem to fix).

**Comment by matwey** [comment] 2021-05-13 10:45
I am working on the JeOS image for Odroid C4 board. This board supports only DOS partition table, since the bootloader should be placed at `512` bytes (`1` sector) offset. Total size of the bootloader image is `1162096` bytes, and it doesn't fit until the first partition with default starting sector `2048`.

So now, I really need both DOS partition table and `disk_start_sector` in the same place.

**Comment by matwey** [comment] 2021-05-19 15:39
I've just noted that there is related workaround in JeOS `u-boot-image-install.in`:

```
    if [ "$force_mbr" ]; then
        # The target system doesn't support GPT, so let's move it to
        # MBR partition layout instead.
        #
        # Also make sure to set the ESP partition to type 0xc so that
        # broken firmware (Rpi) detects it as FAT.

        # Use tabs, "<<-" strips tabs, but no other whitespace!
        cat > gdisk.tmp <<-'EOF'
			x
			r
			g
			t
			1
			c
			w
			y
		EOF
        losetup /dev/loop3 $diskname
        dd if=/dev/loop3 of=mbrid.bin bs=1 skip=440 count=4
        gdisk /dev/loop3 < gdisk.tmp
        dd of=/dev/loop3 if=mbrid.bin bs=1 seek=440 count=4
        losetup -d /dev/loop3
        rm -f mbrid.bin
        rm -f gdisk.tmp
    fi
```

So, lots of boards just ignore `efiparttable="msdos"` and then convert the partition table on its own.

**Comment by StefanBruens** [comment] 2021-05-22 21:16
For all these embedded boards with custom bootloader requirements a unified way to partition the disk would be welcome.

Kiwi has "spare_part", but that is quite coarse granular.
JeOS has several local workarounds.

The requirements for embedded boards are:
- Specify the partition table type
  - GPT preferred
  - MBR when ROM loader uses sector 1 as fixed block address (e.g. Amlogic)
  - MBR when ROM loader parses partition table (e.g. RPi)
- For GPT: specify number of partition entries, if ROM loader uses sector < 32 as fixed block address (e.g. Allwinner)
- Possibility to define one or more "raw" partitions at fixed offsets.

**Comment by schaefi** [comment] 2021-09-06 09:57
This one is open for a long time. One takeaway of the conversation to look into alternative partition tool to create and manage the old dos table. So far we are sticking with fdisk but I will create a new issue to discuss alternatives. However, as long as there is board specific post processing required you will probably always need some "nasty" parts to get the table settled as needed.

kiwi has spare_part as a very simple method also supported in the description. The experience on embedded in the past however shows a very diverse and non standard collection of boards and their way to boot. If there was some sort of standard it was with aarch64 boards aligned to EFI and using uboot as the "EFI firmware". Still on those some special sauce was required which we cannot maintain as part of the builder. That's where the extra scripts and hook in code comes from and I think we need to live with that part.

Regarding custom partition tables this can be done in kiwi with the current script hooks. An example for a full custom setup on x86_64 (just to show how it can be done) is available here:

https://github.com/OSInside/kiwi/tree/master/build-tests/x86/tumbleweed/test-image-custom-partitions

I'm closing this issue now and hope this is ok with everybody, since I don't see a direct change we can do to help
from the kiwi side. I'm very open to make kiwi useful in the embedded world but we need to prevent maintaining board specific source, it will not going to end well.

Feel free to open a new issue if there is more to discuss on this topic. Thanks

**Closed by schaefi** 2021-09-06 09:57 UTC
Labels: Indirect Relation
