### ISSUE TITLE
omit_dracutmodules in dracut config ignored

### ISSUE THREAD

**Issue by Vogtinator** [OSInside/kiwi#1751] opened 2021-03-04 11:54 UTC
kiwi calls `dracut` with `--omit " multipath "`, but that makes it ignore `omit_dracutmodules` in config files.
kiwi writes that to a config file itself, so the parameter seems to be redundant anyway.

**Comment by schaefi** [comment] 2021-03-09 12:59
I could not find where we would write "omit_dracutmodules" for the multipath module. For writing dracut conf files there is a method write_system_config_file() and it is not called for the purpose to omit multipath. Therefore the option has a meaning and cannot just be dropped.

That dracut ignores any omit statement in all config files when you call it with an additional --omit parameter sounds very odd to me. I agree with you if this is the case we have a severe problem. Does it behave the same for other options as well like ```--add`` ? To be honest this sounds a bug or questionable behavior from dracut. It would be fairly fine to construct a list of omit items from config data _and_ caller options.

For us it would be a sensitive change on the dracut call options

The specific multipath case however can be solved by making this a persistent setting in the config file

**Comment by Vogtinator** [comment] 2021-03-09 15:28
> That dracut ignores any omit statement in all config files when you call it with an additional --omit parameter sounds very odd to me. I agree with you if this is the case we have a severe problem. Does it behave the same for other options as well like --add ? To be honest this sounds like a bug or questionable behavior from dracut. It would be fairly fine to construct a list of omit items from config data and caller options.

I was surprised by this as well. It's not documented anywhere AFAICT, I only found it by looking at `/usr/bin/dracut`:

```
# these options add to the stuff in the config file
(( ${#add_dracutmodules_l[@]} )) && add_dracutmodules+=" ${add_dracutmodules_l[@]} "
(( ${#force_add_dracutmodules_l[@]} )) && force_add_dracutmodules+=" ${force_add_dracutmodules_l[@]} "
(( ${#fscks_l[@]} )) && fscks+=" ${fscks_l[@]} "
(( ${#add_fstab_l[@]} )) && add_fstab+=" ${add_fstab_l[@]} "
(( ${#fstab_lines_l[@]} )) && fstab_lines+=( "${fstab_lines_l[@]}" )
(( ${#install_items_l[@]} )) && install_items+=" ${install_items_l[@]} "
(( ${#install_optional_items_l[@]} )) && install_optional_items+=" ${install_optional_items_l[@]} "

# these options override the stuff in the config file
(( ${#dracutmodules_l[@]} )) && dracutmodules="${dracutmodules_l[@]}"
(( ${#omit_dracutmodules_l[@]} )) && omit_dracutmodules="${omit_dracutmodules_l[@]}"
(( ${#filesystems_l[@]} )) && filesystems="${filesystems_l[@]}"
(( ${#fw_dir_l[@]} )) && fw_dir="${fw_dir_l[@]}"
(( ${#libdirs_l[@]} ))&& libdirs="${libdirs_l[@]}"
```

**Comment by schaefi** [comment] 2021-03-29 08:25
> kiwi/kiwi/builder/live.py

right, it's set statically here because for live iso images we don't want multipath support and so it's set in a dracut config file. I wasn't searching for the setting in the live builder

> kiwi/kiwi/builder/disk.py

The setting is part of an if condition

```python
if self.root_filesystem_is_multipath is False:
    self.boot_image.omit_module('multipath')
```

This is only the case if the XML configuration explicitly includes <oem-multipath-scan>false</oem-multipath-scan>.
So by default the disk builder will not make a permanent setting unless requested

**Comment by schaefi** [comment] 2021-03-29 08:31
Overall this is a severe problem for us. I don't see a way for us to change this in kiwi without introducing many unforeseen side effects and regressions.

But thanks for digging into this and sharing the details. We need to take a closer look. Overall the omit information in config files seems to be cumulative, maybe this is just a mistake in dracut ?

**Comment by Vogtinator** [comment] 2021-03-29 08:45
> Overall this is a severe problem for us. I don't see a way for us to change this in kiwi without introducing many unforeseen side effects and regressions.

Write a config file instead of passing it to dracut directly? If it's not meant to be persistent, it could be deleted afterwards.

> But thanks for digging into this and sharing the details. We need to take a closer look. Overall the omit information in config files seems to be cumulative, maybe this is just a mistake in dracut ?

Would be nice, but I don't think so - there's explicit code and comments about this exact behavior.

**Comment by davidcassany** [comment] 2021-03-31 16:11
@schaefi @Vogtinator I just submitted an issue to dracut regarding that, I am curious to know the motivation of the current behavior, it is really unexpected to me and not intuitive.

On the other side I have been checking our code and the `--omit` flag is used for installation media, live images and disk images. 

* Regarding the installation media I'd say we can live with the current behavior, installation media initrd should be pretty simple and it can be easily customized and adapted with the `<installmedia>` section.
* Regarding the live images we can easily avoid the  `--omit` flag, in fact, it is redundant there since we already include a config file with the `omit_dracutmodules+=`
* Regarding disk images we are definitely hit by this problem, the only work around I can think about is by using temporary dracut config file. Our code is prepared to write dracut config files and if we limit it to the use of `--omit` the code refactor wouldn't be huge, but strange to my eyes.

I'd give few days to see if I get some answer to the dracut issue I filled and if not just implement the temporary config file approach, I can't see any other option now.

**Comment by davidcassany** [comment] 2021-04-13 15:43
@schaefi @Vogtinator given that dracut applied the change upstream to behave as we all initially expected I believe there is nothing to change in KIWI.

I'd say the way to go would be to simply include https://github.com/dracutdevs/dracut/pull/1342 into Factory or wait to upgrade dracut on next release.

**Comment by davidcassany** [comment] 2021-07-02 09:01
TW already includes dracut v55 which includes the relevant patch to fix this issue. Closing

**Closed by davidcassany** 2021-07-02 09:01 UTC
Labels: Awaiting Feedback, P2
