### ISSUE TITLE
Missing dmsquash live modules on 9.20 kiwi

### ISSUE THREAD

**Issue by ismacasti** [OSInside/kiwi#1526] opened 2020-08-04 12:13 UTC
## Problem description
LiveCD image built can't boot as built initrd lacks dmsquash-live module.
Error is:
```
Dracut: FATAL: Don't know how to handle 'root=live:CDLABEL=CDROM'
```
Happens on `python3-kiwi-9.20.5-lp151.2.10.1`. It was working fine on `python3-kiwi-9.18.16-lp151.2.6.1`.

## Expected behaviour
Bootable LiveCD image

## Steps to reproduce the behaviour
Both 9.18 and 9.20, we are using this command to build
```
kiwi-ng --color-output --debug --type=iso system create --root=/rootfs/ --target-dir=/home/kiwi/kiwi-target/
```

## OS and Software information
+ KIWI version: python3-kiwi-9.20.5-lp151.2.10.1
+ Operating system: OpenSUSE Leap 15.1
+ OBS version: ?

## Short logs
```
---8<-----
02:52:48 [ INFO    ]: 23:52:45 | --> LOADER_TYPE:grub2-efi
02:52:48 [ INFO    ]: 23:52:45 | --> SECURE_BOOT:yes
02:52:48 [ INFO    ]: 23:52:45 | Creating grub2 live ISO config file from template
02:52:48 [ INFO    ]: 23:52:45 | --> Using standard boot template
02:52:48 [ INFO    ]: 23:52:45 | Writing KIWI template grub.cfg file
02:52:48 [ INFO    ]: 23:52:45 | Copying /home/jenkins/erikube/slave-root/workspace/bm-ovb-deploy-master/kiwi-target/live-media.2jgcfz15/boot/grub2/grub.cfg -> /home/jenkins/erikube/slave-root/workspace/bm-ovb-deploy-master/kiwi-target/live-media.2jgcfz15/EFI/BOOT/grub.cfg to be found by EFI
02:52:48 [ DEBUG   ]: 23:52:45 | EXEC: [qemu-img create /home/jenkins/erikube/slave-root/workspace/bm-ovb-deploy-master/kiwi-target/live-media.2jgcfz15/boot/x86_64/efi 15M]
02:52:48 [ DEBUG   ]: 23:52:45 | EXEC: [mkdosfs -n BOOT /home/jenkins/erikube/slave-root/workspace/bm-ovb-deploy-master/kiwi-target/live-media.2jgcfz15/boot/x86_64/efi]
02:52:48 [ DEBUG   ]: 23:52:45 | EXEC: [mcopy -Do -s -i /home/jenkins/erikube/slave-root/workspace/bm-ovb-deploy-master/kiwi-target/live-media.2jgcfz15/boot/x86_64/efi /home/jenkins/erikube/slave-root/workspace/bm-ovb-deploy-master/kiwi-target/live-media.2jgcfz15/EFI ::]
02:52:48 [ INFO    ]: 23:52:45 | Creating live ISO boot image
02:52:48 [ WARNING ]: 23:52:45 | dracut module "dmsquash-live livenet" not found in the root tree
02:52:48 [ WARNING ]: 23:52:45 | module "dmsquash-live livenet" not included in initrd
02:52:48 [ WARNING ]: 23:52:45 | dracut module "dmsquash-live livenet" not found in the root tree
02:52:48 [ INFO    ]: 23:52:45 | Creating generic dracut initrd archive
02:52:48 [ DEBUG   ]: 23:52:45 | EXEC: [cp /tmp/tmpxrnlkx_g /tmp/tmpar8nv93h]
02:52:48 [ DEBUG   ]: 23:52:45 | EXEC: [bash -c source /usr/lib/python3.6/site-packages/kiwi/config/functions.sh; baseQuoteFile /tmp/tmpar8nv93h]
02:52:48 [ DEBUG   ]: 23:52:45 | --> kiwi_align='1048576'
02:52:48 [ DEBUG   ]: 23:52:45 | --> kiwi_cmdline='verbose ds=nocloud net.ifnames=1 rd.writable.fsimg'
---8<-----
```
On the older kiwi, those warnings do not appear and the image is fully functional

**Comment by schaefi** [comment] 2020-08-10 13:20
This looks like a duplicate of #1431, an update to 9.20.12 or higher should fix it

**Closed by schaefi** 2020-08-10 13:20 UTC
