### ISSUE TITLE
Support for installing Flatpak applications

### ISSUE THREAD

**Issue by kevinsmia1939** [OSInside/kiwi#1193] opened 2019-09-05 18:24 UTC
Support setting up Flathub repository (https://flathub.org/repo/flathub.flatpakrepo) and installing flatpak applications.

**Comment by dcermak** [comment] 2019-09-11 12:20
I've asked the flatpak developers and according to them installing a flatpak is just a filesystem operation, so technically it should work inside kiwi. Do you have an error message from kiwi when you tried to install a flatpak?

**Comment by schaefi** [comment] 2019-09-13 07:53
@kevinsmia1939 guess the open question is for you. Can you answer the question ? Thanks

**Comment by kevinsmia1939** [comment] 2019-09-20 22:45
I'm same guy in matrix, just putting this error down here for now.

config.xml include flatpak and gpg2 packages.
config.sh include these 2 lines:
(trying to install openra with faltpak)
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install -vv --ostree-verbose flathub net.openra.OpenRA

The error found within image-root.log is as shown below.

error: GPG: Unable to configure context: No such file or directory
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Both min-free-space-percent and -size are mentioned in config. Enforcing min-free-space-size check only.
F: Opening user flatpak installation at path /root/.local/share/flatpak
F: Fetching summary file for remote ?flathub?
F: Adding GPG keyring dir /usr/share/ostree/trusted.gpg.d to verifier
F: Failed to download optional summary
error: Unable to load summary from remote flathub: GPG: No such file or directory

**Comment by dcermak** [comment] 2019-09-23 14:38
@kevinsmia1939 Could you provide your full kiwi recipe (config.sh, kiwi.xml and overlays, if present)?

**Comment by kevinsmia1939** [comment] 2019-09-24 00:01
`<?xml version="1.0" encoding="utf-8"?>

<image schemaversion="6.8" name="KalaOS-Tumbleweed">
    <description type="system">
        <author>Kavin_Tee</author>
        <contact>kevin_tee@pm.me</contact>
        <specification>
            KalaOS - Breaking myth and misconception, glimps into the new territory
        </specification>
    </description>
    <preferences>
        <type image="iso" primary="true" flags="overlay" hybrid="true" hybridpersistent_filesystem="ext4" hybridpersistent="true"/>
        <version>1.99.1</version>
        <packagemanager>zypper</packagemanager>
        <locale>en_US</locale>
        <keytable>us</keytable>
        <timezone>Asia/Bangkok</timezone>
        <rpm-excludedocs>true</rpm-excludedocs>
        <rpm-check-signatures>false</rpm-check-signatures>
        <bootsplash-theme>bgrt</bootsplash-theme>
        <bootloader-theme>openSUSE</bootloader-theme>
    </preferences>
    <preferences>
        <type image="vmx" filesystem="ext4" bootloader="grub2" kernelcmdline="splash" firmware="efi"/>
        <type image="oem" filesystem="ext4" initrd_system="dracut" installiso="true" bootloader="grub2" kernelcmdline="splash" firmware="efi">
            <oemconfig>
                <oem-systemsize>2048</oem-systemsize>
                <oem-swap>true</oem-swap>
                <oem-device-filter>/dev/ram</oem-device-filter>
                <oem-multipath-scan>false</oem-multipath-scan>
                <oem-unattended>false</oem-unattended>
            </oemconfig>
            <machine memory="512" guestOS="suse" HWversion="4">
                <vmdisk id="0" controller="ide"/>
                <vmnic driver="e1000" interface="0" mode="bridged"/>
            </machine>
        </type>
    </preferences>
    <users>
        <user password="1234" pwdformat="plain" home="/root" name="root" groups="root"/>
        <user password="1234" pwdformat="plain" home="/home/tux" name="tux" groups="tux"/>
    </users>
    <repository type="yast2" alias="Tumbleweed-Oss" imageinclude="true" priority="99">
        <source path="http://download.opensuse.org/tumbleweed/repo/oss"/>
    </repository>
    <repository type="yast2" alias="openSUSE-Tumbleweed-Non-Oss" imageinclude="true" priority="99">
        <source path="http://download.opensuse.org/tumbleweed/repo/non-oss/"/>
    </repository>
    <repository type="yast2" alias="openSUSE-Tumbleweed-Update" imageinclude="true" priority="99">
        <source path="http://download.opensuse.org/update/tumbleweed/"/>
    </repository>
    <repository type="yast2" alias="Science" imageinclude="true" priority="90">
        <source path="https://download.opensuse.org/repositories/science/openSUSE_Tumbleweed/"/>
    </repository>
    <repository type="yast2" alias="MultiMedia" imageinclude="true" priority="100">
        <source path="https://download.opensuse.org/repositories/multimedia:/apps/openSUSE_Tumbleweed/"/>
    </repository>
    <repository type="rpm-md" alias="VSCodium" imageinclude="true" priority="99">
        <source path="https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/rpms/"/>
    </repository>
    <repository type="rpm-md" alias="NVIDIA" imageinclude="true" priority="99">
        <source path="https://download.nvidia.com/opensuse/tumbleweed/"/>
    </repository>
    <packages type="image" patternType="plusRecommended">
        <namedCollection name="base"/>    
        <namedCollection name="enhanced_base"/>    
        <namedCollection name="fonts"/>
        <namedCollection name="x11"/>  
        <namedCollection name="kde"/>  
        <namedCollection name="kde_plasma"/>
        <namedCollection name="yast2_basis"/>
        <package name="desktop-data-openSUSE-extra"/>
        <package name="yast2-qt-branding-openSUSE"/>
        <package name="yast2-control-center"/>
        <package name="yast2-fonts"/>
        <package name="htop"/>
        <package name="ksystemlog"/>
        <package name="libreoffice"/>
        <package name="libreoffice-gtk3"/>
        <package name="libreoffice-gnome"/>
        <package name="libreoffice-l10n-th"/>
        <package name="thai-fonts"/>
        <package name="testdisk"/>
        <package name="kate"/>
        <package name="psmisc"/>
        <package name="command-not-found"/>
        <package name="sudo"/>
        <package name="libsecret-1-0"/>
        <package name="iproute2"/>
        <package name="python2-SecretStorage"/>
        <package name="xorg-x11-server"/>
        <package name="fuse-exfat"/>
        <package name="exfat-utils"/>
        <package name="python"/>
        <package name="perl"/>
        <package name="plymouth-theme-bgrt"/>
        <package name="plymouth-dracut"/>
        <package name="grub2-branding-openSUSE"/>
        <package name="ifplugd"/>
        <package name="iputils"/>
        <package name="vim"/>
        <package name="grub2"/>
        <package name="grub2-i386-pc"/>
        <package name="syslinux"/>
        <package name="flatpak"/>
        <package name="gpg2"/>
        <package name="lvm2"/>
        <package name="plymouth"/>
        <package name="fontconfig"/>
        <package name="fonts-config"/>
        <package name="coreutils"/>
        <package name="curl"/>
        <package name="gawk"/>
        <package name="w3m"/>
        <package name="mktemp"/>
        <package name="cabextract"/>
        <package name="tar"/>
        <package name="unzip"/>
        <package name="gzip"/>
        <package name="parted"/>
        <package name="openssh"/>
        <package name="iproute2"/>
        <package name="sensors"/>
        <package name="libQt5Sensors5"/>
        <package name="libsensors4"/>
        <package name="hddtemp"/>
        <package name="less"/>
        <package name="bash-completion"/>
        <package name="dhcp-client"/>
        <package name="which"/>
        <package name="kernel-default"/>
        <package name="timezone"/>
    </packages>
    <packages type="image" patternType="onlyRequired">
        <package name="lame"/>
        <package name="gstreamer-plugins-bad"/>
        <package name="gstreamer-plugins-ugly"/>
        <package name="gstreamer-plugins-libav"/>
        <package name="libavdevice58"/>
    </packages>
    <packages type="iso">
        <package name="gfxboot-branding-openSUSE"/>
        <package name="dracut-kiwi-live"/>
    </packages>
    <packages type="oem">
        <package name="gfxboot-branding-openSUSE"/>
        <package name="dracut-kiwi-oem-repart"/>
        <package name="dracut-kiwi-oem-dump"/>
    </packages>
    <packages type="bootstrap">
        <package name="udev"/>
        <package name="filesystem"/>
        <package name="glibc-locale"/>
        <package name="cracklib-dict-full"/>
        <package name="ca-certificates"/>
        <package name="ca-certificates-mozilla"/>
        <package name="openSUSE-release"/>
    </packages>
</image>
`

**Comment by kevinsmia1939** [comment] 2019-09-24 00:02
> <?xml version="1.0" encoding="utf-8"?>

<image schemaversion="6.8" name="KalaOS-Tumbleweed">
    <description type="system">
        <author>Kavin_Tee</author>
        <contact>kevin_tee@pm.me</contact>
        <specification>
            KalaOS - Breaking myth and misconception, glimps into the new territory
        </specification>
    </description>
    <preferences>
        <type image="iso" primary="true" flags="overlay" hybrid="true" hybridpersistent_filesystem="ext4" hybridpersistent="true"/>
        <version>1.99.1</version>
        <packagemanager>zypper</packagemanager>
        <locale>en_US</locale>
        <keytable>us</keytable>
        <timezone>Asia/Bangkok</timezone>
        <rpm-excludedocs>true</rpm-excludedocs>
        <rpm-check-signatures>false</rpm-check-signatures>
        <bootsplash-theme>bgrt</bootsplash-theme>
        <bootloader-theme>openSUSE</bootloader-theme>
    </preferences>
    <preferences>
        <type image="vmx" filesystem="ext4" bootloader="grub2" kernelcmdline="splash" firmware="efi"/>
        <type image="oem" filesystem="ext4" initrd_system="dracut" installiso="true" bootloader="grub2" kernelcmdline="splash" firmware="efi">
            <oemconfig>
                <oem-systemsize>2048</oem-systemsize>
                <oem-swap>true</oem-swap>
                <oem-device-filter>/dev/ram</oem-device-filter>
                <oem-multipath-scan>false</oem-multipath-scan>
                <oem-unattended>false</oem-unattended>
            </oemconfig>
            <machine memory="512" guestOS="suse" HWversion="4">
                <vmdisk id="0" controller="ide"/>
                <vmnic driver="e1000" interface="0" mode="bridged"/>
            </machine>
        </type>
    </preferences>
    <users>
        <user password="1234" pwdformat="plain" home="/root" name="root" groups="root"/>
        <user password="1234" pwdformat="plain" home="/home/tux" name="tux" groups="tux"/>
    </users>
    <repository type="yast2" alias="Tumbleweed-Oss" imageinclude="true" priority="99">
        <source path="http://download.opensuse.org/tumbleweed/repo/oss"/>
    </repository>
    <repository type="yast2" alias="openSUSE-Tumbleweed-Non-Oss" imageinclude="true" priority="99">
        <source path="http://download.opensuse.org/tumbleweed/repo/non-oss/"/>
    </repository>
    <repository type="yast2" alias="openSUSE-Tumbleweed-Update" imageinclude="true" priority="99">
        <source path="http://download.opensuse.org/update/tumbleweed/"/>
    </repository>
    <repository type="yast2" alias="Science" imageinclude="true" priority="90">
        <source path="https://download.opensuse.org/repositories/science/openSUSE_Tumbleweed/"/>
    </repository>
    <repository type="yast2" alias="MultiMedia" imageinclude="true" priority="100">
        <source path="https://download.opensuse.org/repositories/multimedia:/apps/openSUSE_Tumbleweed/"/>
    </repository>
    <repository type="rpm-md" alias="VSCodium" imageinclude="true" priority="99">
        <source path="https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/rpms/"/>
    </repository>
    <repository type="rpm-md" alias="NVIDIA" imageinclude="true" priority="99">
        <source path="https://download.nvidia.com/opensuse/tumbleweed/"/>
    </repository>
    <packages type="image" patternType="plusRecommended">
        <namedCollection name="base"/>    
        <namedCollection name="enhanced_base"/>    
        <namedCollection name="fonts"/>
        <namedCollection name="x11"/>  
        <namedCollection name="kde"/>  
        <namedCollection name="kde_plasma"/>
        <namedCollection name="yast2_basis"/>
        <package name="desktop-data-openSUSE-extra"/>
        <package name="yast2-qt-branding-openSUSE"/>
        <package name="yast2-control-center"/>
        <package name="yast2-fonts"/>
        <package name="htop"/>
        <package name="ksystemlog"/>
        <package name="libreoffice"/>
        <package name="libreoffice-gtk3"/>
        <package name="libreoffice-gnome"/>
        <package name="libreoffice-l10n-th"/>
        <package name="thai-fonts"/>
        <package name="testdisk"/>
        <package name="kate"/>
        <package name="psmisc"/>
        <package name="command-not-found"/>
        <package name="sudo"/>
        <package name="libsecret-1-0"/>
        <package name="iproute2"/>
        <package name="python2-SecretStorage"/>
        <package name="xorg-x11-server"/>
        <package name="fuse-exfat"/>
        <package name="exfat-utils"/>
        <package name="python"/>
        <package name="perl"/>
        <package name="plymouth-theme-bgrt"/>
        <package name="plymouth-dracut"/>
        <package name="grub2-branding-openSUSE"/>
        <package name="ifplugd"/>
        <package name="iputils"/>
        <package name="vim"/>
        <package name="grub2"/>
        <package name="grub2-i386-pc"/>
        <package name="syslinux"/>
        <package name="flatpak"/>
        <package name="gpg2"/>
        <package name="lvm2"/>
        <package name="plymouth"/>
        <package name="fontconfig"/>
        <package name="fonts-config"/>
        <package name="coreutils"/>
        <package name="curl"/>
        <package name="gawk"/>
        <package name="w3m"/>
        <package name="mktemp"/>
        <package name="cabextract"/>
        <package name="tar"/>
        <package name="unzip"/>
        <package name="gzip"/>
        <package name="parted"/>
        <package name="openssh"/>
        <package name="iproute2"/>
        <package name="sensors"/>
        <package name="libQt5Sensors5"/>
        <package name="libsensors4"/>
        <package name="hddtemp"/>
        <package name="less"/>
        <package name="bash-completion"/>
        <package name="dhcp-client"/>
        <package name="which"/>
        <package name="kernel-default"/>
        <package name="timezone"/>
    </packages>
    <packages type="image" patternType="onlyRequired">
        <package name="lame"/>
        <package name="gstreamer-plugins-bad"/>
        <package name="gstreamer-plugins-ugly"/>
        <package name="gstreamer-plugins-libav"/>
        <package name="libavdevice58"/>
    </packages>
    <packages type="iso">
        <package name="gfxboot-branding-openSUSE"/>
        <package name="dracut-kiwi-live"/>
    </packages>
    <packages type="oem">
        <package name="gfxboot-branding-openSUSE"/>
        <package name="dracut-kiwi-oem-repart"/>
        <package name="dracut-kiwi-oem-dump"/>
    </packages>
    <packages type="bootstrap">
        <package name="udev"/>
        <package name="filesystem"/>
        <package name="glibc-locale"/>
        <package name="cracklib-dict-full"/>
        <package name="ca-certificates"/>
        <package name="ca-certificates-mozilla"/>
        <package name="openSUSE-release"/>
    </packages>
</image>

**Comment by kevinsmia1939** [comment] 2019-09-24 00:05
I have to rename it to .txt for github to upload the file.

[config.sh.txt](https://github.com/OSInside/kiwi/files/3644606/config.sh.txt)
[config.xml.txt](https://github.com/OSInside/kiwi/files/3644607/config.xml.txt)

**Comment by davidcassany** [comment] 2019-11-14 10:32
closing this issue since there is nothing in KIWI preventing flatpak usage, i managed to install flatpak applicacions using

```
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install -y -vv --ostree-verbose --noninteractive flathub net.openra.OpenRA
flatpak install -y -vv --ostree-verbose --noninteractive flathub com.slack.Slack
```
in my config.sh. I am not fecing any gpg issue, it looks like there might be some gpg utility missing, in the provided example. Note I had to add noninteractive and assume yes flags to get it working.

**Closed by davidcassany** 2019-11-14 10:32 UTC
Labels: Enhancement

**Comment by aplanas** [comment] 2019-11-14 10:34
maybe the outcome can be a documentation about the config that make this case succeed?

**Comment by davidcassany** [comment] 2019-11-15 10:10
Yes the procedure I followed is quite simple. I used the Leap 15.1 image from [OSInside/kiwi-descriptions](https://github.com/OSInside/kiwi-descriptions/tree/master/suse/x86_64/suse-leap-15.1-JeOS). In config.xml I added the following packages:

```xml
<package name="flatpak"/>
<package name="ca-certificates-mozilla"/> <!-- needed for certs verification of flatpak repos -->
```

In config.sh I added the following:

```bash
#==========================================
# Add flatpak apps
#------------------------------------------
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install -y -vv --ostree-verbose --noninteractive flathub net.openra.OpenRA
```

Then executed

```
kiwi-ng --type iso --debug system build --description <path_to_kiwi_prj> --target-dir /tmp/my_test_image
```

and successfully build, the config.sh stdout was:

```
DEBUG: 17:07:51 | --------------out start-------------
DEBUG: 17:07:51 | Configure image: [LimeJeOS-Leap-15.1]...
DEBUG: 17:07:56 | /etc/products.d /
DEBUG: 17:07:56 | /
DEBUG: 17:53:49 | Installing runtime/org.freedesktop.Platform/x86_64/18.08
DEBUG: 17:53:52 | Installing runtime/org.freedesktop.Platform.GL.nvidia-390-132/x86_64/1.4
DEBUG: 17:54:36 | --------------out stop--------------
```

Note the installation of the selected flatpak plus the related dependencies took about one hour. I first tried also with the Slack package, as in the example attached with this issue, however I cancelled the build after more than two hours of waiting for the flatpak installation to finalize.

**Comment by dcermak** [comment] 2019-11-15 10:26
David Cassany Viladomat <notifications@github.com> writes:

> Yes the procedure I followed is quite simple. I used the Leap 15.1 image from [OSInside/kiwi-descriptions](https://github.com/OSInside/kiwi-descriptions/tree/master/suse/x86_64/suse-leap-15.1-JeOS). In config.xml I added the following packages:
>
> ```xml
> <package name="flatpak"/>
> <package name="ca-certificates-mozilla"/> 
> ```
>
> In config.sh I added the following:
>
> ```bash
> #==========================================
> # Add flatpak apps
> #------------------------------------------
> flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
> flatpak install -y -vv --ostree-verbose --noninteractive flathub net.openra.OpenRA
> ```
>
> Then executed
>
> ```
> kiwi-ng --type iso --debug system build --description <path_to_kiwi_prj> --target-dir /tmp/my_test_image
> ```
>
> and successfully build, the config.sh stdout was:
>
> ```
> DEBUG: 17:07:51 | --------------out start-------------
> DEBUG: 17:07:51 | Configure image: [LimeJeOS-Leap-15.1]...
> DEBUG: 17:07:56 | /etc/products.d /
> DEBUG: 17:07:56 | /
> DEBUG: 17:53:49 | Installing runtime/org.freedesktop.Platform/x86_64/18.08
> DEBUG: 17:53:52 | Installing runtime/org.freedesktop.Platform.GL.nvidia-390-132/x86_64/1.4

This might actually be a problem: you are implicitly installing the
Nvidia platform (because your machine probably has a Nvidia card,
right?). This _could_ cause issues on machines which don't have a Nvidia
graphics card, but I am not sure about that (never tried that).

> DEBUG: 17:54:36 | --------------out stop--------------
> ```
>
> Note the installation of the selected flatpak plus the related dependencies took about one hour. I first tried also with the Slack package, as in the example attached with this issue, however I cancelled the build after more than two hours of waiting for the flatpak installation to finalize.
>

That is suspiciously long. And I mean like REALLY long. Usually flatpaks
install very quickly, even on my ancient Thinkpad x200 they install &
update in minutes not hours (installation is far quicker than
downloading)! (The upgrade consumes excessive amounts of RAM though, but
that is a different story).

**Comment by davidcassany** [comment] 2019-11-15 11:35
> Usually flatpaks install very quickly, even on my ancient Thinkpad x200 they install & update in minutes not hours (installation is far quicker than downloading)!

Well in my case it downloaded several GB of data... it took quite a long to download all the stuff. I have no idea how flatpak does the dependency resolution but if it is based on the host hardware this is clearly an issue for imaging. Now I curious to runt he same image build on VM and see if it pulls the same.

In any case I can't see anything wrong from KIWI POV.

**Comment by dcermak** [comment] 2019-11-15 11:47
David Cassany Viladomat <notifications@github.com> writes:

>> Usually flatpaks install very quickly, even on my ancient Thinkpad x200 they install & update in minutes not hours (installation is far quicker than downloading)!
>
> Well in my case it downloaded several GB of data... it took quite a long to download all the stuff. I have no idea how flatpak does the dependency resolution but if it is based on the host hardware this is clearly an issue for imaging. Now I curious to runt he same image build on VM and see if it pulls the same.
>

It kind of doesn't have to do dependency resolution, at least not a lot,
because flatpaks are expected to bundle more or less everything beside
some generic runtimes (e.g. GNOME, Nvidia runtime).

> In any case I can't see anything wrong from KIWI POV.

Neither do I. I just don't think that we should actually recommend
people to do this, unless we are certain that the pulled in flatpak
works and doesn't require not present runtimes (which could maybe
occur).

**Comment by kevinsmia1939** [comment] 2020-10-02 21:26
Some update,

I use OBS to build the ISO image, which I have tried to install flatpak and flatpak apps on it.
Download the ISO image and run it in VM.
Then when in KDE desktop, run `flatpak list` to see list of flatpak packages.
No flatpak app found.

https://build.opensuse.org/package/show/home:andythe_great:branches:Virtualization:Appliances:Images:Testing_x86:suse/flatpak-test

**Comment by davidcassany** [comment] 2020-10-05 07:29
@kevinsmia1939 Take into account that what you are trying to achieve is not possible. By design OBS builds are done in an environment without internet connection. It is done this way to be capable to guarantee the reproducibility of the build, to ensure all the required sources and binaries are available and stored somewhere inside OBS.

To install flatpaks in OBS you must find a procedure to prevent any buildtime download. I have no experience with flatpak, but as far as I could see with a quick search seams to be a tricky goal.

The alternative could be installing flatpak toolchain and set a one time service at boot that installs desired flatpaks on firstboot.

**Comment by kevinsmia1939** [comment] 2020-10-08 18:33
> @kevinsmia1939 Take into account that what you are trying to achieve is not possible. By design OBS builds are done in an environment without internet connection. It is done this way to be capable to guarantee the reproducibility of the build, to ensure all the required sources and binaries are available and stored somewhere inside OBS.
> 
> To install flatpaks in OBS you must find a procedure to prevent any buildtime download. I have no experience with flatpak, but as far as I could see with a quick search seams to be a tricky goal.
> 
> The alternative could be installing flatpak toolchain and set a one time service at boot that installs desired flatpaks on firstboot.

็Hello,
How about building image locally? I have tried it, while the build pass without the error, I tried running the ISO image in virtualbox it does not show any flatpak installed.

**Comment by davidcassany** [comment] 2020-10-09 08:25
> Hello,
> How about building image locally? I have tried it, while the build pass without the error, I tried running the ISO image in virtualbox it does not show any flatpak installed.

well, I just run again the same test I did in https://github.com/OSInside/kiwi/issues/1193#issuecomment-554298914 and again I had an equivalent resutl. The installation does not fail. The resulting images includes several additional GB as the results of downloading many ostree like blobs. After booting `flatpak list` lists the required flatpak plus some additional dependencies. The logs shows a wide rage of messages in the stderr of `config.sh` execution. I got several messages like the following in between tons of other downloading traces

```
F: extracting extra data to /var/lib/flatpak/runtime/org.freedesktop.Platform.openh264/x86_64/2.0/.73f998362a6fc0d57e0c7e83e928d32b0ec14d10d0d94291033976bdcecc6b6b-RRNMS0/files/extra
F: Disallowing ipc access                                                       
F: Disallowing network access                                                   
F: Failed to run in transient scope: No systemd user session available, cgroups not available
F: Running /app/bin/apply_extra                                                 
bwrap: Failed to make / slave: Invalid argument                                 
Warning: Failed to install org.freedesktop.Platform.openh264: While trying to apply extra data: apply_extra script failed, exit status 256
 ```
Doesn't look very good. To me looks like flatpak relies on the host setup for several operations (to identify dependencies, to run certain install scripts, etc), so this is likely to have erratic behavior in chroot environments and also making it hard to be used in imaging systems, where the root tree is filled within a different hardware.

I still have the same opinion. I don't think it should be advised to use flatpak in `config.sh` as flatpak seams not to be designed to be used in such a context. I don't see any KIWI related issue here, to me it looks more like limitations of flatpak.

From KIWI PoV a feasible workaround is what I just mentioned in https://github.com/OSInside/kiwi/issues/1193#issuecomment-703454543 about creating a systemd one shot unit that installs any desired flatpak during the firstboot so once you hit the login prompt everything is set and ready. Obviously this might be tricky for live images.

**Comment by beardogg0524** [comment] 2023-08-12 02:15
Here's the weird thing. When I run "flatpak instasll openh264" in a regular terminal, it installs just fine. However, when I run the same command in CUBIC (I develop a Debian Sid remaster), it fails to install. Is it an issue with CUBIC, or is it simply not possible to install as root?

**Comment by dcermak** [comment] 2023-08-12 09:00
beardogg0524 ***@***.***> writes:

> Here's the weird thing. When I run "flatpak instasll openh264" in a regular terminal, it installs just fine. However, when I run the same command in CUBIC (I develop a Debian Sid remaster), it fails to install. Is it an issue with CUBIC, or is it simply not possible to install as root?

It is most certainly possible to install flatpaks as root (at least on
both Fedora and openSUSE, but I doubt it would be different on other
distros).

Do you see this issue on a running system or inside a kiwi build?
