### ISSUE TITLE
setfiles command fails

### ISSUE THREAD

**Issue by neel-parikh** [OSInside/kiwi#2244] opened 2023-02-14 20:58 UTC
https://github.com/OSInside/kiwi/blob/4d6b8412431e6b0d27321921bd1cb7caa5ec847f/kiwi/system/setup.py#L542

The above line has an extra "/" at the end due to which setfiles command fails during kiwi build:

[2023-02-14T20:35:53.786Z] [ DEBUG   ]: 20:35:53 | EXEC: [chroot image-root setfiles -F -p -c /etc/selinux/targeted/policy/policy.32 -e /proc -e /sys -e /dev /etc/selinux/targeted/contexts/files/file_contexts /]
[2023-02-14T20:35:54.049Z] [ DEBUG   ]: 20:35:53 | EXEC: Failed with stderr: usage:  setfiles [-diIDlmnpqvFW] [-e excludedir] [-r alt_root_path] spec_file pathname...
[2023-02-14T20:35:54.049Z] usage:  setfiles [-diIDlmnpqvFW] [-e excludedir] [-r alt_root_path] spec_file -f filename
[2023-02-14T20:35:54.049Z] usage:  setfiles -s [-diIDlmnpqvFW] spec_file
[2023-02-14T20:35:54.049Z] usage:  setfiles -c policyfile spec_file
[2023-02-14T20:35:54.049Z] , stdout: (no output on stdout)
[2023-02-14T20:35:54.049Z] [ ERROR   ]: 20:35:53 | KiwiCommandError: chroot: stderr: usage:  setfiles [-diIDlmnpqvFW] [-e excludedir] [-r alt_root_path] spec_file pathname...

I tried to run on a native SUSE OS it fails as below:

[root@tmp]# setfiles -F -p -c /etc/selinux/targeted/policy/policy.31 -e /proc -e /sys -e /dev /etc/selinux/targeted/contexts/files/file_contexts /
usage:  setfiles [-dilnpqvFW] [-e excludedir] [-r alt_root_path] spec_file pathname...
usage:  setfiles [-dilnpqvFW] [-e excludedir] [-r alt_root_path] spec_file -f filename
usage:  setfiles -s [-dilnpqvFW] spec_file
usage:  setfiles -c policyfile spec_file

OS: openSUSE 15.3
Kiwi version: 9.24.43

**Comment by schaefi** [comment] 2023-03-10 22:49
This is confusing. setfiles = selilnux, suse = apparmor. kiwi calls setfiles only if there is an selinux security policy installed which typically exists on RHEL/Fedora systems. The integration test we have for this is here:

* https://build.opensuse.org/package/live_build_log/Virtualization:Appliances:Images:Testing_x86:fedora/test-image-live-disk:Virtual/images/x86_64

So it succeeded the way setfiles is called here.

The story around setfiles is very confusing to me. It seems the tool exists in different versions and incompatible caller formats which makes it really hard for kiwi to do it right all the time.

Thus if you can clarify on the exact target, setfiles version, architecture and maybe @iammattcoleman or @Conan-Kudo can you clarify on that setfiles mystery :)

Thanks much

**Comment by dirkmueller** [comment] 2023-03-14 08:23
> This is confusing. setfiles = selilnux, suse = apparmor.

openSUSE is actually both selinux and apparmor, with apparmor being the current default.

Other SUSE products like ALP and some SLE product variants like micro only support selinux (and have it enabled by default)

**Comment by schaefi** [comment] 2023-03-14 10:52
Ah good to know, that wasn't clear to me. So there are also security policies for selinux on openSUSE.
I think we need an integration test image that uses selinux like it is described here:

* https://doc.opensuse.org/documentation/leap/security/html/book-security/cha-selinux.html 

Maybe that helps to identify parts of the issue here

**Comment by schaefi** [comment] 2023-03-14 14:08
Takeaways form the community meeting:

- The setfiles call in kiwi has a weird line of processing which was added to keep RHEL7 compatibility. Since EL7 is out of scope for kiwi anyway this code part should be dropped
- To get a better understanding if selinux works on SUSE an integration test build should be created with help from the above docs. In case the build fails we are up for a conversation why.

I sign up for working on this

**Comment by dirkmueller** [comment] 2023-03-14 17:55
@schaefi let me know if there's an issue with rhe selinux integration image. Don't expect it as we have it already in some products (I could only imagine that there's a workaround somewhere that would require upstreaming)

**Comment by schaefi** [comment] 2023-03-15 10:31
@dirkmueller I have opened a pull request with an integration test to build an selinux enabled image for leap. The setfiles call worked for me. Thus I cannot reproduce the original issue reported here. In any case it would be good if you and @neel-parikh can take a look at the build test and give it a test (simply run in qemu).

I'd like to understand if/what needs to change in kiwi.

Thanks

**Comment by neel-parikh** [comment] 2023-03-15 21:18
@schaefi Thanks for looking into this. Apparently, I'm only seeing the issue with these policies
https://download.opensuse.org/repositories/security:/SELinux_legacy/15.3/

But the kiwi command works for these:
https://download.opensuse.org/repositories/security:/SELinux/SLE_15_SP3/

The later rpms were having conflicts so I was using the old one to try it out.

**Closed** 2023-04-24 07:17 UTC
