### ISSUE TITLE
Encryption does not work on Debian

### ISSUE THREAD

**Issue by ozboss** [OSInside/kiwi#1992] opened 2021-11-26 16:10 UTC
### Full disk encryption

Full disk encryption (`bootpartition="false"`) does not work at all with Debian, because by default it encrypts with LUKS2 and Grub currently cannot handle LUKS2. Apparently openSUSE uses LUKS1 by default and that's why it works here (see #1898).
If this is incorrect please let me know, otherwise it would be nice if this was documented. 

### Encrypted root

With `bootpartition="true"` it is possible at least encrypt root, which is nice :)
But here no proper crypttab is created, so that any following `update-initramfs` (which is a normal operation on Debbian) will make the system unbootable.
For the crypttab to be correct it additionally needs the cipher and the term `initramfs`, which it is currently missing.

## Expected behaviour

During installation a fully defined and working crypttab is created.

## Steps to reproduce the behaviour

- Create a Debian OEM image
- Install the image
- Run `update-initramfs`

## OS and Software information
+ KIWI version: 9.24.6
+ Operating system: Debian 10
+ OBS version: -

**Comment by schaefi** [comment] 2021-11-29 09:09
@ozboss Thanks for the report, you are completely right with what you said. We did not had time to look into LUKS2 and all testing is also based on LUKS1. Regarding the "grub cannot read from LUKS2" issue, I have seen this with ```cryptomount```
being non functional in this case. I assume at this end we can only wait for grub to support it

> With bootpartition="true" it is possible at least encrypt root, which is nice :)

:)

> But here no proper crypttab is created, so that any following update-initramfs (which is a normal operation on Debbian)
will make the system unbootable. For the crypttab to be correct it additionally needs the cipher and the term initramfs, which it is currently missing.

I think at this point we could fix kiwi to do the right thing. From what you have said I'm not entirely clear what changes must be done. In kiwi and if there is a key file we write the crypttab like this:

* https://github.com/OSInside/kiwi/blob/master/kiwi/storage/luks_device.py#L159

From my perspective this was enough information to open the crypto pool (interactive ask for the passphrase is usually handled at the app level opening the pool, e.g systemd)

Could you help us here, maybe with an example crypttab ?

Thanks much

**Comment by Conan-Kudo** [comment] 2021-11-29 12:29
LUKS2 support was added in GRUB 2.06, which is not present in any release of Debian or Ubuntu yet.

**Comment by Conan-Kudo** [comment] 2021-11-29 14:44
We would wind up using the cryptsetup format supported by dracut, which should match what other distros have.

**Comment by ozboss** [comment] 2021-11-29 14:59
Well this is what I meant with `update-initramfs` is a "normal" operation on Debian.
Users working on a Debian based install expect this command to work and I just feel like if you really want to support building theses kind of images it should comply with the default system tools of the OS.

**Comment by Conan-Kudo** [comment] 2021-11-29 15:01
Both Dracut and initramfs-tools are supported in Debian. Our goal is to support with distro-agnostic tooling, not with adding tons of distro-specific stuff.

**Comment by rasentry** [comment] 2021-11-30 17:36
I get similar problem with openSUSE Tumbleweed. If I use `bootpartition="false"` grub shows command line and I am trying to mount crypto disk with `cryptomount -a` nothing happens.
With `bootpartition="true"` grub shows menu but still doesn't see crypto disk. Luks v2

**Comment by schaefi** [comment] 2021-11-30 18:38
> I get similar problem with openSUSE Tumbleweed. If I use `bootpartition="false"` grub shows command line and I am trying to mount crypto disk with `cryptomount -a` nothing happens. With `bootpartition="true"` grub shows menu but still doesn't see crypto disk. Luks v2

yes, same issue on TW. The last working version is with Leap 15.3. I hope this grub problem will be fixed soon. We have an integration test for luks encryption here:

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:tumbleweed/test-image-luks

it shows the same issue, cryptomount does nothing

**Comment by rasentry** [comment] 2021-11-30 19:50
Here is what I found out:  
In grub command line :  
With `bootpartition="false"`:  
`lsmod` - shows only `luks` module loaded
`insmod luks2` - module is not found  

With `bootpartition="true"`:   
`lsmod` - shows only `luks` module loaded (no `luks2` module)
`insmod luks2` - ok
`cryptomount -a` - asks for passphrase but tells my password is wrong (I tried the same passphrase with `cryptsetup luksOpen` it is ok)

**Comment by ozboss** [comment] 2022-02-06 15:47
Just to get back to the original issue:

> Both Dracut and initramfs-tools are supported in Debian. Our goal is to support with distro-agnostic tooling, not with adding tons of distro-specific stuff.

I can total understand your decision and it was just my lack of knowledge that caused me some trouble until I figured out how kiwi works differently from standard Debian.
Maybe its possible to add a little section about things like that, also to make sure to include packages for kiwi features that you want to use in your image, like btrfs and cryptsetup.
I think that would make it a lot easier for beginners.

I will leave the issue open for now but feel free to close it.

**Comment by schaefi** [comment] 2022-07-12 13:48
@ozboss In the meantime the support for luks2 and the opportunity to select on those options were added and documented: 

* https://osinside.github.io/kiwi/image_description/elements.html?highlight=luks2

>Maybe its possible to add a little section about things like that, also to make sure to include packages for kiwi features that 
you want to use in your image, like btrfs and cryptsetup.

Could you give me a short refresher what exactly you meant by that ? Is it related to dracut which requires the tools it uses for its own modules to be installed ?

Thanks

**Comment by schaefi** [comment] 2023-01-05 09:23
This is sitting for a long time. I assume the issue is resolved regarding my last comment and no further information based on it. If there is more just let us know. Thanks

**Closed by schaefi** 2023-01-05 09:23 UTC
Labels: Doc
