### ISSUE TITLE
Systemd for debian buster is not building anymore

### ISSUE THREAD

**Issue by phoenixflare** [OSInside/kiwi#2063] opened 2022-02-10 19:31 UTC
## Problem description
Debian buster appears to be failing to build the systemd image. This issue was not present in 9.24.10 but is present in 9.24.21. This was tested on 2 separate machines running 9.24.10 and confirmed it was working. After the upgrade to 9.24.21, the same image gave the error. I have also tested the debian-buster image from kiwi-descriptions and it has the same error.

`[ DEBUG   ]: 11:00:21 | system: Processing triggers for systemd (241-7~deb10u8) ...
[ INFO    ]: Processing: [########################################] 100%
[ ERROR   ]: 11:00:21 | KiwiInstallPhaseFailed: System package installation failed: perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LC_CTYPE = "en_US.UTF-8",
        LANG = "C"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
debconf: delaying package configuration, since apt-utils is not installed
E: Can not write log (Is /dev/pts mounted?) - posix_openpt (19: No such device)
Created symlink /etc/systemd/system/getty.target.wants/getty@tty1.service → /lib/systemd/system/getty@.service.
Created symlink /etc/systemd/system/multi-user.target.wants/remote-fs.target → /lib/systemd/system/remote-fs.target.
Created symlink /etc/systemd/system/dbus-org.freedesktop.timesync1.service → /lib/systemd/system/systemd-timesyncd.service.
Created symlink /etc/systemd/system/sysinit.target.wants/systemd-timesyncd.service → /lib/systemd/system/systemd-timesyncd.service.
Initializing machine ID from random generator.
Generating locales (this might take a while)...
Generation complete.
Generating /etc/default/kexec...
Running in chroot, ignoring request: daemon-reload
Running in chroot, ignoring request.
Running in chroot, ignoring request: daemon-reload
Running in chroot, ignoring request: is-active
Running in chroot, ignoring request: start
Running in chroot, ignoring request: daemon-reload
Running in chroot, ignoring request.
Running in chroot, ignoring request: daemon-reload
Running in chroot, ignoring request: is-active
Running in chroot, ignoring request: start
W: mdadm: failed to load MD subsystem.
Generating mdadm.conf... done (failed to scan arrays; /proc probably not mounted).
Running in chroot, ignoring request: daemon-reload
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-5.8.5
Adding boot menu entry for EFI firmware configuration
done
Running in chroot, ignoring request: daemon-reload
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
Running in chroot, ignoring request: daemon-reload
Running in chroot, ignoring request: daemon-reload
Running in chroot, ignoring request.
Running in chroot, ignoring request: daemon-reload
Running in chroot, ignoring request: is-active
Running in chroot, ignoring request: start
chown: invalid group: 'root:staff'
dpkg: error processing package fontconfig-config (--configure):
 installed fontconfig-config package post-installation script subprocess returned error exit status 1
Running in chroot, ignoring request: daemon-reload
Running in chroot, ignoring request: daemon-reload
Running in chroot, ignoring request: daemon-reload
Running in chroot, ignoring request: daemon-reload
Created symlink /etc/systemd/system/multi-user.target.wants/networking.service → /lib/systemd/system/networking.service.
Created symlink /etc/systemd/system/network-online.target.wants/networking.service → /lib/systemd/system/networking.service.
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-5.8.5
Adding boot menu entry for EFI firmware configuration
done
dpkg: dependency problems prevent configuration of plymouth-themes:
 plymouth-themes depends on fontconfig-config; however:
  Package fontconfig-config is not configured yet.

dpkg: error processing package plymouth-themes (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libfontconfig1:amd64:
 libfontconfig1:amd64 depends on fontconfig-config (>= 2.13.1-2); however:
  Package fontconfig-config is not configured yet.

dpkg: error processing package libfontconfig1:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libpangoft2-1.0-0:amd64:
 libpangoft2-1.0-0:amd64 depends on libfontconfig1 (>= 2.13.0); however:
  Package libfontconfig1:amd64 is not configured yet.

dpkg: error processing package libpangoft2-1.0-0:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libpangocairo-1.0-0:amd64:
 libpangocairo-1.0-0:amd64 depends on libfontconfig1 (>= 2.12.6); however:
  Package libfontconfig1:amd64 is not configured yet.
 libpangocairo-1.0-0:amd64 depends on libpangoft2-1.0-0 (>= 1.28.1); however:
  Package libpangoft2-1.0-0:amd64 is not configured yet.

dpkg: error processing package libpangocairo-1.0-0:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of plymouth-label:
 plymouth-label depends on libpangocairo-1.0-0 (>= 1.14.0); however:
  Package libpangocairo-1.0-0:amd64 is not configured yet.

dpkg: error processing package plymouth-label (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of fontconfig:
 fontconfig depends on libfontconfig1 (>= 2.13.0); however:
  Package libfontconfig1:amd64 is not configured yet.
 fontconfig depends on fontconfig-config; however:
  Package fontconfig-config is not configured yet.

dpkg: error processing package fontconfig (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libpango-1.0-0:amd64:
 libpango-1.0-0:amd64 depends on fontconfig (>= 2.1.91); however:
  Package fontconfig is not configured yet.

dpkg: error processing package libpango-1.0-0:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libcairo2:amd64:
 libcairo2:amd64 depends on libfontconfig1 (>= 2.12.6); however:
  Package libfontconfig1:amd64 is not configured yet.

dpkg: error processing package libcairo2:amd64 (--configure):
 dependency problems - leaving unconfigured
/usr/lib/dracut/dracut-functions.sh: line 703: btrfs: command not found
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
Running in chroot, ignoring request: daemon-reload
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
Running in chroot, ignoring request: daemon-reload
Created symlink /etc/systemd/system/sockets.target.wants/dm-event.socket → /lib/systemd/system/dm-event.socket.
Running in chroot, ignoring request: daemon-reload
Running in chroot, ignoring request: is-active
dm-event.service is a disabled or a static unit, not starting it.
Running in chroot, ignoring request: is-active
Running in chroot, ignoring request: start
Running in chroot, ignoring request.
Running in chroot, ignoring request: daemon-reload
Running in chroot, ignoring request: is-active
Running in chroot, ignoring request: start
Running in chroot, ignoring request: daemon-reload
Running in chroot, ignoring request: daemon-reload
Running in chroot, ignoring request: daemon-reload
Running in chroot, ignoring request.
Running in chroot, ignoring request: daemon-reload
Running in chroot, ignoring request: is-active
Running in chroot, ignoring request: start
Created symlink /etc/systemd/system/sysinit.target.wants/blk-availability.service → /lib/systemd/system/blk-availability.service.
Created symlink /etc/systemd/system/sysinit.target.wants/lvm2-monitor.service → /lib/systemd/system/lvm2-monitor.service.
Running in chroot, ignoring request: daemon-reload
Running in chroot, ignoring request: is-active
Running in chroot, ignoring request: is-active
Running in chroot, ignoring request: start
Created symlink /etc/systemd/system/sysinit.target.wants/lvm2-lvmpolld.socket → /lib/systemd/system/lvm2-lvmpolld.socket.
Running in chroot, ignoring request: daemon-reload
Errors were encountered while processing:
 fontconfig-config
 plymouth-themes
 libfontconfig1:amd64
 libpangoft2-1.0-0:amd64
 libpangocairo-1.0-0:amd64
 plymouth-label
 fontconfig
 libpango-1.0-0:amd64
 libcairo2:amd64
W: No sandbox user '_apt' on the system, can not drop privileges
E: Sub-process /usr/bin/dpkg returned an error code (1)

[ INFO    ]: 11:00:21 | Cleaning up SystemPrepare instance
[ DEBUG   ]: 11:00:21 | EXEC: [mountpoint -q /var/tmp/tmpa9gp8qtq/kiwi-build/build/image-root/run]
[ DEBUG   ]: 11:00:21 | EXEC: [mountpoint -q /var/tmp/tmpa9gp8qtq/kiwi-build/build/image-root/run]
[ DEBUG   ]: 11:00:21 | EXEC: [umount -l /var/tmp/tmpa9gp8qtq/kiwi-build/build/image-root/run]
[ DEBUG   ]: 11:00:21 | EXEC: [mountpoint -q /var/tmp/tmpa9gp8qtq/kiwi-build/build/image-root/sys]
`

## OS and Software information
+ KIWI version: 9.24.21
+ Operating system: OpenSUSE Tumbleweed

**Comment by schaefi** [comment] 2022-02-13 14:20
> E: Can not write log (Is /dev/pts mounted?) - posix_openpt (19: No such device)

Hmm, I don't think this is caused by something we changed in kiwi. As of now I could also not imagine what should have caused it. So far I was not able to reproduce the issue you mentioned. I have checked our integration tests from here:

* https://build.opensuse.org/project/show/Virtualization:Appliances:Images:Testing_x86:debian

and I have done a local build in an adequate build environment for a Debian build which should be a Debian based distro

```
 kiwi-ng system boxbuild --box ubuntu -- --description ~ms/Project/kiwi-descriptions/debian/x86_64/debian-buster/ --target-dir /tmp/mytest-debian
```

This also built without issues. For details on how to install the boxbuild plugin see:
https://osinside.github.io/kiwi/plugins/self_contained.html

Unless there is a reproducer for the issue in obs or locally when building in a "compatible" environment I can't do much.

On a site note: Building Debian based images on TW with the debian tooling from there and on a distro that changes every minute is not an environment which I would trust much. That's also why we build all integration test builds in obs using a project setup of the distribution of the target image.

Just for fun I was also testing the user and group issue you had in your other issue report and could also not reproduce this.
I admit I have not tested building debian images on TW. I'm sorry this is just not stable enough for me to investigate deeply what's going on. We don't do this on other rolling releases too e.g rawhide. However there is a kiwi box called "universal"
for the above mentioned kiwi box plugin and that is based on Fedora 34 and the tooling there for apt, dpk, pacman, zypper...
is astonishing working well for different distro builds. With TW however, we often have very weird issues like the ones you
reported.

I Hope this makes sense to you too and I hope we find a solution

Thanks

**Comment by phoenixflare** [comment] 2022-02-13 23:25
Just spun up a fresh install of OS 15.3 to test. Pulled the 9.24.23 package from [OBS:Server:Unstable](https://build.opensuse.org/project/show/OBS:Server:Unstable) and it runs into the same issue.

I believe this is the only issue I opened? The user and group issue isn't me. The other person just happened to post an issue shortly after I did.

I'm just using `kiwi-ng --debug system build --description=/root/kiwi-descriptions/debian/x86_64/debian-buster --target-dir /tmp/testbuild` so it shouldn't be doing anything too different from the OBS build.

**Comment by schaefi** [comment] 2022-02-14 09:14
>Just spun up a fresh install of OS Leap 15.3 to test. Pulled the 9.24.23 package from OBS:Server:Unstable and it runs into the same issue.

ok, thanks for the reproducer. I'll try that

> I believe this is the only issue I opened?

so sorry I was mixing up things :)

**Comment by phoenixflare** [comment] 2022-02-17 03:22
That looks more like network issue halfway through the build. Here's my full log if you're interested. Not that it's going to help anymore than the previous logs =)
And I agree, debian is painful. There is so much about the debian repos that I want to complain about.
[debianbuild.txt](https://github.com/OSInside/kiwi/files/8085296/debianbuild.txt)

**Comment by schaefi** [comment] 2022-07-12 14:21
Sorry for the late reply. I was also not successful building Debian buster on a Leap host with debian tooling installed. I'm afraid but I don't think it's an issue on the kiwi side because running the same kiwi but inside of a Debian (Ubuntu) system worked for me. You can do the same when using the ```boxbuild``` approach as I wrote in my comment on Feb 13th.

Actually I think for Debian based distros it would be preferable to run image builds on Debian based host systems to prevent the tooling nightmare.

I hope you don't mind but I won't have time to dig further into this issue and going to close on behalf of the boxbuild solution. Please create a new issue if you think this is a defect that has to be fixed in kiwi code

Thanks

**Closed by schaefi** 2022-07-12 14:21 UTC
