### ISSUE TITLE
package dracut-kiwi-oem-repart is not installed

### ISSUE THREAD

**Issue by classy-giraffe** [OSInside/kiwi#1843] opened 2021-06-08 09:48 UTC
## Problem description
```
[ INFO    ]: 07:25:08 | Cleaning up SystemPrepare instance
[ INFO    ]: 07:25:08 | Creating system image
[ ERROR   ]: 07:25:08 | KiwiCommandError: rpm: stderr: (no output on stderr), stdout: package dracut-kiwi-oem-repart is not 
installed
```
I've been getting this error since yesterday even though the said package is available inside the ISO, just by looking at this:
```
DEBUG: 08:58:52 | system: Installed:                                
DEBUG: 08:58:53 | system:   dracut-049-135.git20210121.el8.x86_64                                         
DEBUG: 08:58:53 | system:   dracut-kiwi-lib-9.23.34-1.el8.noarch                                          
DEBUG: 08:58:53 | system:   dracut-kiwi-oem-dump-9.23.34-1.el8.noarch                                     
DEBUG: 08:58:53 | system:   dracut-kiwi-oem-repart-9.23.34-1.el8.noarch                                   
DEBUG: 08:58:53 | system:   dracut-network-049-135.git20210121.el8.x86_64                                 
DEBUG: 08:58:53 | system:   dracut-squash-049-135.git20210121.el8.x86_64 
```

## Expected behaviour
Virtual Disk OEM building just fine.

## Steps to reproduce the behaviour
Invoking kiwi like this:
```
kiwi-ng --color-output \
    --profile Disk system boxbuild --box fedora -- \
    --description . \
    --target-dir result/
```
```xml
<image schemaversion="6.8" name="ASVi">
    <profiles>
        <profile name="Disk" description="Simple Disk image"/>
    </profiles>
    <preferences>
        <version>8.3.0</version>
        <packagemanager>dnf</packagemanager>
        <locale>en_US</locale>
        <keytable>us</keytable>
        <timezone>UTC</timezone>
        <rpm-check-signatures>false</rpm-check-signatures>
    </preferences>
    <preferences profiles="Disk">
        <type image="oem" initrd_system="dracut" filesystem="xfs" installiso="true" installboot="install" bootloader="grub2" kernelcmdline="loglevel=0" firmware="uefi">
        </type>
    </preferences>
    <users>
        <user password="$1$wYJUgpM5$RXMMeASDc035eX.NbYWFl0" home="/root" name="root" groups="root"/>
    </users>
    <repository type="rpm-md" alias="AlmaLinux8-BaseOS" imageinclude="true">
        <source path="https://repo.almalinux.org/almalinux/8/BaseOS/x86_64/os/"/>
    </repository>
    <repository type="rpm-md" alias="AlmaLinux8-AppStream" imageinclude="true">
        <source path="https://repo.almalinux.org/almalinux/8/AppStream/x86_64/os/"/>
    </repository>
    <repository type="rpm-md" alias="AlmaLinux8-PowerTools" imageinclude="true">
        <source path="https://repo.almalinux.org/almalinux/8/PowerTools/x86_64/os/"/>
    </repository>
    <repository type="rpm-md" alias="AlmaLinux8-Extras" imageinclude="true">
        <source path="https://repo.almalinux.org/almalinux/8/extras/x86_64/os/"/>
    </repository>
    <repository type="rpm-md" alias="EPEL8-Everything" imageinclude="true">
        <source path="https://download.fedoraproject.org/pub/epel/8/Everything/x86_64/"/>
    </repository>
    <packages type="image" profiles="Disk">
        <namedCollection name="core"/>
        <package name="syslinux"/>
        <package name="grub2"/>
        <package name="kernel"/>
        <package name="epel-release"/>
        <package name="binutils"/>
    </packages>
    <packages type="image" profiles="Disk">
        <package name="dracut-kiwi-oem-repart"/>
        <package name="dracut-kiwi-oem-dump"/>
    </packages>
    <packages type="bootstrap" profiles="Disk">
        <package name="filesystem"/>
        <package name="basesystem"/>
        <package name="grub2-efi-x64-modules"/>
        <package name="grub2-efi-x64"/>
        <package name="shim-x64" arch="x86_64"/>
    </packages>
</image>
```

## OS and Software information
+ KIWI version: latest from OBS (with the container plugin)
+ Operating system: OpenSUSE tumbleweed

**Comment by schaefi** [comment] 2021-06-11 09:23
Hmm, strange. Can you provide the complete build log ```/result/result.log``` in your case

Thanks

**Comment by schaefi** [comment] 2021-06-11 09:39
Ah I can reproduce this issue. The reason is this check: #1822

**Comment by schaefi** [comment] 2021-06-11 09:40
The kiwi in the boxes (fedora in your case) do not have the kiwi with this fix because I did not yet create a new release

**Comment by schaefi** [comment] 2021-06-11 09:45
This issue will self heal as soon as a new kiwi release will be out and the boxes rebuilds with it.

As a workaround you can call:

```
kiwi-ng --color-output \
    --profile Disk system boxbuild --box fedora --kiwi-version 9.23.37 -- \
    --description . \
    --target-dir result/
```

This will update the kiwi in the box to the selected version (latest from pip) and runs the build with it
For me this has fixed the issue

**Comment by schaefi** [comment] 2021-06-11 09:47
Let me know if that works for you too. Thanks

**Comment by classy-giraffe** [comment] 2021-06-21 07:28
It does, perfect. Thank you so much!

**Comment by schaefi** [comment] 2021-09-06 09:44
closing, as boxes builds with a kiwi that has the fix now. Thanks

**Closed by schaefi** 2021-09-06 09:44 UTC
Labels: Awaiting Feedback
