### ISSUE TITLE
Obsolete python2-kiwi in spec file

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1413] opened 2020-04-24 09:52 UTC
## Problem description

Before py2 was EOL kiwi supported both versions and built a sub-package named python2-kiwi. After we dropped support for py2 some version of this package is still around. Thus the current spec file should obsolete python2-kiwi

## Expected behaviour

python2-kiwi is not used anymore

**Comment by schaefi** [comment] 2020-04-24 09:53
Thanks to Fabian who pointed this out

**Comment by davidcassany** [comment] 2020-04-24 10:20
I think this a duplicate of this bsc#1156677

**Comment by schaefi** [comment] 2020-05-11 09:25
Along with this there is another bugzilla report that could be fixed in the same spot:

https://bugzilla.suse.com/show_bug.cgi?id=1168973

**Closed** 2020-05-18 11:35 UTC
Labels: Bug
