### ISSUE TITLE
repo-alias is not url but chars/numbers

### ISSUE THREAD

**Issue by lorenzen-b1** [OSInside/kiwi#1247] opened 2019-10-23 12:04 UTC
## Problem description
When adding a repo w/o `alias` kiwi will not " construct an alias from the path in the source child element (replacing each / with a _), if no value is given" but generate a checksum or something

## Expected behaviour
generate an alias from the URL as stated in 
https://osinside.github.io/kiwi/working_with_kiwi/xml_description.html#adding-repositories

## Steps to reproduce the behaviour
add a repo like this:
```
  <repository type="rpm-md" imageonly="true" alias="">
    <source path="https://repo.$region.foo/something/suse/update/"/>
  </repository>
```
And you end up with this config in the image:
```
> cat /etc/zypp/repos.d/11c9e6da365ea81e2346411aeb590868.repo
[11c9e6da365ea81e2346411aeb590868]
enabled=1
autorefresh=1
baseurl=https://repo.$region.foo/something/suse/update/
type=rpm-md
keeppackages=1
```

I get the same result when i dont set `alias` at all.

## OS and Software information
+ KIWI version: 9.17.16
+ Operating system: SLES 15SP0
+ OBS version: -

**Comment by davidcassany** [comment] 2019-10-25 09:47
Thanks for reporting.

I think that's been the intended behavior for quite some time (already some years) and the documentation does not reflect the current behavior. This is a documentation issue, the code is just fine, the alies is defined according to the URI with this code https://github.com/OSInside/kiwi/blob/1ead12bbc3292c89fe531de350d21b808f8c4970/kiwi/system/uri.py#L159-L172

This is safer than just swaping `/` by `_` as there could be different repositories resolving to the same alias.

Docs needs to be updated to reflect the current behavior.

**Comment by lorenzen-b1** [comment] 2019-10-28 10:50
thanks, i'll provide updated docs in the next few days

**Closed** 2019-11-15 15:10 UTC
Labels: Doc, Enhancement, P1
