### ISSUE TITLE
LVM: "system create" fails. /dev/mapper/* and /dev/<vg>/* not removed

### ISSUE THREAD

**Issue by t-ru** [OSInside/kiwi#1897] opened 2021-08-03 21:06 UTC
## Problem description
Hello,

I'm try to create a image with the follow disk description:

<preferences profiles="sles-vmware,sles4sap-vmware">

		<type 
			image="oem" 
			filesystem="xfs" 
			format="vmdk" 
			firmware="uefi" 
			bootpartition="false" 
			devicepersistency="by-uuid"
			fscreateoptions="-i sparse=0"
			kernelcmdline="plymouth.enable=0 console=ttyS0,115200 console=tty0 mitigations=auto vmw_pvscsi.cmd_per_lun=1024 vmw_pvscsi.ring_pages=32 quiet">
			
			<bootloader name="grub2" timeout="10"/>

			<systemdisk name="system">
				<volume name="@root=root" size="30G"/>
			</systemdisk>

			<oemconfig>
				<oem-resize>false</oem-resize>
				<oem-swap>true</oem-swap>
				<oem-swapsize>20480</oem-swapsize>
				<oem-swapname>swap</oem-swapname>
			</oemconfig>          
		</type>

	</preferences>

LVM. VG = system. LV = root, LV = swap

The 1. run of "system create" creates the image sucessfully.

The 2. run of "system create" fails.

```
[ ERROR   ]: 22:43:40 | KiwiCommandError: vgcreate: stderr:   /dev/system: already exists in filesystem
  Run `vgcreate --help' for more information.
```

The cleanup doesn't work in run 1.

```
INFO: 22:38:06 | Cleaning up FileSystemFat16 instance
INFO: 22:38:06 | umount FileSystemFat16 instance
DEBUG: 22:38:06 | EXEC: [mountpoint -q /var/tmp/kiwi_mount_manager.jtk54u61]
DEBUG: 22:38:06 | EXEC: [umount /var/tmp/kiwi_mount_manager.jtk54u61]
INFO: 22:38:06 | Cleaning up VolumeManagerLVM instance
DEBUG: 22:38:06 | EXEC: [mountpoint -q /var/tmp/kiwi_volumes.etk4k1dc]
DEBUG: 22:38:06 | EXEC: [vgchange --config devices/external_device_info_source=none -an system]
INFO: 22:38:07 | Cleaning up FileSystemSwap instance
INFO: 22:38:07 | Cleaning up Disk instance
DEBUG: 22:38:07 | EXEC: [dmsetup remove /dev/mapper/loop0p1]
DEBUG: 22:38:07 | EXEC: [dmsetup remove /dev/mapper/loop0p2]
DEBUG: 22:38:07 | EXEC: [dmsetup remove /dev/mapper/loop0p3]
INFO: 22:38:07 | Cleaning up LoopDevice instance
DEBUG: 22:38:07 | EXEC: [losetup -d /dev/loop0]
```
No errors.

```
ls -ltr /dev/mapper

total 0
crw------- 1 root root  10, 236 Aug  3 19:29 control
brw------- 1 root root 253,   0 Aug  3 22:36 loop0p1
brw-r----- 1 root    6 253,   4 Aug  3 22:36 system-root
brw-r----- 1 root    6 253,   3 Aug  3 22:36 system-swap
brw------- 1 root root 253,   1 Aug  3 22:43 loop0p2
brw------- 1 root root 253,   2 Aug  3 22:43 loop0p3
```
loop0pX is not removed in run 1.

```
ls -ltr /dev/system

total 0
lrwxrwxrwx 1 root root 23 Aug  3 22:36 swap -> /dev/mapper/system-swap
lrwxrwxrwx 1 root root 23 Aug  3 22:36 root -> /dev/mapper/system-root
```
/dev/system  is not removed in run 1.

```
dmsetup remove -f /dev/mapper/loop0p1

device-mapper: table ioctl on loop0p1  failed: No such device or address
device-mapper: reload ioctl on loop0p1  failed: No such device or address
device-mapper: remove ioctl on loop0p1  failed: No such device or address
Command failed.
```

`vgs`

... not result.

`pvs`

... not result.

`lvs`

... not result.

Logs

[run_1_system_create.log](https://github.com/OSInside/kiwi/files/6927053/run_1_system_create.log)
[run_2_system_create.log](https://github.com/OSInside/kiwi/files/6927048/run_2_system_create.log)

## Expected behaviour

/dev/mapper/* should be removed.
/dev/system/* should be removed.

## Steps to reproduce the behaviour

see Problem description.

## OS and Software information
+ KIWI version: KIWI (next generation) version 9.23.49
+ Operating system: openSUSE Tumbleweed (20210801) @ Windows Subsystem for Linux (WSL 2)
+ OBS version: no OBS

**Comment by schaefi** [comment] 2021-08-04 11:02
Hmm, that's bad.I need to check your first log to see if it has at least tried to release the resources

**Comment by t-ru** [comment] 2021-08-04 12:08
Hello schaefi,

I'm currently rewriting my build scripts. Reason is that no derived builds are possible. The base image description (I'm used) are available at:

- base image: https://github.com/t-ru/os-images/images/sle-15-3.vmware. 
- derived image: https://github.com/t-ru/os-images/tree/master/images/sle-15-3.vmware.sap-as. 

What does the my build script do?

Step 1: configure
Step 2: system create with "--add-package"
Step 3: system image

everything standard. no bad things

**Comment by schaefi** [comment] 2021-08-04 15:02
I took a look to the ```run_1_system_create.log``` but I can't see that it does anything with LVM, search for vgcreate in the log and it has no matches... consequently no cleanup of that part. Is this the correct log ?

**Comment by t-ru** [comment] 2021-08-04 18:18
I made a new run 1. this is is the correct log

[image.log](https://github.com/OSInside/kiwi/files/6933531/image.log)

**Comment by schaefi** [comment] 2021-08-05 09:41
I'll give it a test now

**Comment by schaefi** [comment] 2021-08-05 09:52
Hmm, I copy pasted your type definition and build a TW image with it on a Leap 15.2 host. The cleanup worked and the commands I see in your log also looks good

* Can you confirm you have lvmetad disabled on your build host
  https://documentation.commvault.com/commvault/v11/article?p=104318.html
  This always causes issues

* Can you confirm you don't run LVM as part of the rootfs(/) on the host you build the image on ?

* Do you run this inside of a container ?

**Comment by t-ru** [comment] 2021-08-05 11:46
> * Do you run this inside of a container ?

No. But in WSL2. I think that is the same. I've no systemctl. My /etc/lvm/lvm.conf has no entry for "use_lvmetad".

**Comment by schaefi** [comment] 2021-08-05 13:20
Hmm, ok so you are running this in a WSL container on Windows. I've never done that so far. Problem is, I can't easily reproduce this in my environment and I can't find anything wrong in the sequence of cleanup.

Hmm

**Comment by t-ru** [comment] 2021-08-05 13:56
Running kiwi in WSL2 is the same as running kiwi in a docker or podman container. Both has no systemd.

Do you have a laptop with windows 10 and wsl2? If yes, I can send you powershell script that creates my wsl2 thumbleweed kiwi appliance

**Comment by schaefi** [comment] 2021-08-05 15:08
No Windows here in my office ;) That's a lame excuse I know. (btw with podman you can run containers with systemd, quite nice for fat containers)

I see if I can run this in a container.

It would be helpful if you can do some post debugging after the create step when you realize there are resources still open. In the kiwi log file you already found the calls kiwi did and I do not understand why it does not work. If the calls would have failed there would be exception messages. So these actions went through but didn't had an effect.

For example

```
dmsetup remove /dev/mapper/loop0p3
```

and you get

```
device-mapper: table ioctl on loop0p3  failed: No such device or address
```

If this happens there is no chance for kiwi to cleanup. If you get this on docker I know what the problem is.
It's libdevmapper incompatible between host and guest in container OS.

If the host is Windows I actually don't know how this is mapped.

In both cases you need extended permissions to run an image build in a container (permissive mode)
This is the source of all evil to run image builds in containers because now you share a lot with the host
including kernel, kernel filesystems, libdevmapper and more.

This is the reason why the kiwi box plugin was implemented to run on kvm

Now you are on Windows so I can understand the WSL choice but I'm not sure if the issue you reported
can be fixed

Do you get any chance to cleanup the open resources in your WSL env, or do you have to restart it ?

**Comment by schaefi** [comment] 2021-09-06 10:10
I'm closing this one now and hope you don't mind. I tested builds in docker and podman and given the host vs. container system incompatiblity is not an easy all of the cleanup sequence works.

As soon as I'm using a host that has an incompatible version of libdevmapper compared to libdevmapper running in the container and you perform actions that requires the container to be privileged, meaning device node handling, loops and alike I get similar resource issues as you have seen it

I haven't done testing on windows with WSL containers. However, there is nothing kiwi can do better on the Linux side with the devmapper issue and the same applies also to the WSL environment. If ```dmsetup remove``` comes back with an error an a device that was used before, I wonder how you will ever be able to get rid of it, other than stopping the container. That part I'd say is outside of kiwi's responsibility ;)

**Closed by schaefi** 2021-09-06 10:10 UTC
Labels: Bug, blocked
