### ISSUE TITLE
Fix kiwi spec regarding former python2-kiwi

### ISSUE THREAD

**Issue by schaefi** [OSInside/kiwi#1645] opened 2020-12-07 15:14 UTC
## Problem description

The current setting in the kiwi spec to pull in python3-kiwi and replace python2-kiwi correctly is not quite correct.
The correct setting should be

```
Provides: python2-kiwi = %{version}
Obsoletes: python2-kiwi < %{version}
```

This needs to be done in

- [ ] upstream
- [ ] sle_12 repo
- [ ] sle_15 repo

and submitted upstream as well as to:

```
SUSE:SLE-12-SP2:Update/python-kiwi
SUSE:SLE-12-SP4:Update/python-kiwi 
SUSE:SLE-12-SP5:Update/python-kiwi 
SUSE:SLE-15-SP1:Update/python-kiwi
```

**Comment by Conan-Kudo** [comment] 2020-12-07 17:04
This package should _not_ provide `python2-kiwi`. Doing so makes it so that people think the Python 2 stack will work.

**Comment by davidcassany** [comment] 2020-12-07 17:25
I understand this might be confusing. However the idea is to provide a solution to packages requiring `python2-kiwi`, so the package manager finds a solution by  installing python3-kiwi if possible. I agree this might be misleading to anyone trying to explicitly install `python2-kiwi` as the package manager will solve it by installing `python3-kiwi`, but if not any package requiring `python2-kiwi` is stuck to the latest version of `python-kiwi` including both, as the `python3-kiwi` obsoletes python2 version.

**Comment by Conan-Kudo** [comment] 2020-12-07 17:27
This should remain broken though, because if someone is doing `import kiwi` stuff, that _definitely_ won't work from Python 2.

**Comment by davidcassany** [comment] 2020-12-07 17:29
> This should remain broken though, because if someone is doing `import kiwi` stuff, that _definitely_ won't work from Python 2.

Well yes, good point. :thinking: 

Then probably the only reasonable solution is to go after anyone requiring `python2-kiwi`.

**Comment by Conan-Kudo** [comment] 2020-12-07 17:48
Yup. So I'm going to close this because the status quo is correct.

**Comment by davidcassany** [comment] 2020-12-08 08:07
Well if you don't mind I am reopening, I am not that convinced the status quo is that correct. If python3-kiwi is not a drop-in replacement for `python2-kiwi` I am wondering if it is correct to obsolete it in `python3-kiwi` and include a conflict for it.

**Comment by schaefi** [comment] 2020-12-08 09:13
> If python3-kiwi is not a drop-in replacement for python2-kiwi

why is it not a drop in replacement ? because a py2 program doesn't see kiwi from an api perspective ? From a command-line perspective it is a drop in replacement as it is the same source. So how do we define "drop in replacement" ?

**Comment by davidcassany** [comment] 2020-12-08 10:22
I mean, anyone using python2-kiwi API in a python2 project can't simply start using python3-kiwi API. @Conan-Kudo noted it in https://github.com/OSInside/kiwi/issues/1645#issuecomment-740063281 and he got a point IMHO. From an API PoV if a simple `zypper up` switches from python2-kiwi to python3-kiwi in a seamless way it will just silently break the python stack. This only works fine for anyone using the `kiwi-ng` command, which I guess is the vast majority if not all, but this doesn't change the fact that `python3-kiwi` providing `python2-kiwi` is not correct, as it doesn't work with the python2 stack.

I starting to believe that probably we should have just dropped `python2-kiwi` without any `Obsolete` and  `Conflict` so anyone that the is stuck with python2 stack is capable to keep using the deprecated python2-kiwi without getting any updates and at the same time install the latest python3-kiwi without getting any dependency break. Then we should look after projects requiring python2-kiwi and suggest them to move to python3-kiwi.

This is not a very appealing approach, but if we aim to not break anything and let users upgrade without facing conflicts I guess this could be a reasonable behavior.

To me it seams we need to agree on the expected behavior first and consider two cases: packages that use the command line as a dependency and packages that make use the API, for which the python2 stack can't be switched from py2 to py3 in an automated and transparent fashion.

**Comment by schaefi** [comment] 2020-12-08 11:12
I agree completely to what you and @Conan-Kudo have said. 

> we should have just dropped python2-kiwi

This is not really possible on suse. Even if you drop a package its old binary version is still around. The drop only affects the channels from which customers fetches packages. In the internal data structures a binary package will exist forever. obs always has a chance to pick it up. Also the policy for a package drop requires to either obsolete or provide it by some other package if there is a successor. The successor for python2-kiwi is clearly python3-kiwi. As you are right that it's not a drop-in-replacement from an API perspective the status quo seems to be the correct setting

In the end the solution I was aiming for, that by no means python2-kiwi is picked up is probably not possible

**Comment by Conan-Kudo** [comment] 2020-12-08 11:54
This is the weakness of the structure of the packaging as it is now (which SUSE distributions have promoted for a long time), where the CLI was part of the API package. When I packaged this in Fedora, I split it because I originally provided both Python 2 and Python 3, while only providing the Python 3 powered CLI via a different subpackage. I never used alternatives, and I never allowed CLI and API to be conflated.

**Comment by schaefi** [comment] 2020-12-08 11:59
yes I think you are very much right on this. Actually the cli tool should be just one implementation using the API.

Now we know but should this be changed in the spec and when ? kiwi 10 ?

**Comment by Conan-Kudo** [comment] 2020-12-08 12:01
Yeah, this is probably a KIWI 10 thing. We can break a ton of assumptions when we're ready with v10.

**Comment by schaefi** [comment] 2020-12-08 12:06
agreed. I've added this to the card:

* https://github.com/OSInside/kiwi/projects/2#column-6265815

**Comment by schaefi** [comment] 2020-12-08 12:10
With this particular issue here we are still nowhere and iirc leaving the current setting is the way to go.

Then let's wait for @davidcassany since he re-opened for a valid reason, but I doubt there is a solution, a drop of python2-kiwi will not help in the obs case since binaries stay forever. python2-kiwi is marked to be not released in the channel files so that old binary will not be accessible by customers which is like a drop imho.

**Comment by davidcassany** [comment] 2020-12-09 08:55
> > we should have just dropped python2-kiwi
> 
> This is not really possible on suse. Even if you drop a package its old binary version is still around. The drop only affects the channels from which customers fetches packages. In the internal data structures a binary package will exist forever. 

I think I did not explain myself properly. What I am wondering about is if makes sense to just remove the current `Obsoletes: python2-kiwi` and `Conflicts: python2-kiwi` so no conflicts are created in any case. The problem of this approach is that `python2-kiwi` will remain outdated and without any obvious hint to users to point this is a deprecated package.

I am not a fan of this solution, that's why I though about agreeing on a reasonable behavior with the given constraints. In fact I am fine with leaving the things as they are, just want to be explicit that this our choice to then approach to the affected packages to change python2-kiwi requirements to python3-kiwi if possible (AFAIK, at SUSE, this is only a problem for the JeOS kiwi templates).

> In the end the solution I was aiming for, that by no means python2-kiwi is picked up is probably not possible

Yes, I believe this is not really possible with the standard release workflow we have.

**Comment by Vogtinator** [comment] 2020-12-09 09:42
> The problem of this approach is that python2-kiwi will remain outdated and without any obvious hint to users to point this is a deprecated package.

`Obsoletes` don't actually achieve that either. If you have an obsolete package on your system, you won't actually see that anywhere directly. What it actually does depends on what you're doing with `rpm`/`zypper`: If there's a "chance" to install `python3-kiwi` instead, it'll do it, but otherwise nothing changes.

It seems like there isn't any way for packages to `Requires: kiwi > 9.20` or whatever currently, which would at least solve the issue for `kiwi-templates-JeOS`.

**Comment by Conan-Kudo** [comment] 2020-12-09 11:38
> It seems like there isn't any way for packages to `Requires: kiwi > 9.20` or whatever currently, which would at least solve the issue for `kiwi-templates-JeOS`.

This was something I thought of when I packaged it for Fedora, but when I talked about doing this in the upstream packaging years ago, I was told this was intentionally not done. So this is a major difference between Fedora and upstream packaging.

**Comment by davidcassany** [comment] 2020-12-09 16:50
Closing it as with the current packaging setup the status quo seams to be a reasonable approach. Sorry for making this discussion longer to finally end up where we already were. Anyway I am glad the discussion served to put this on KIWI 10 list.

**Closed by davidcassany** 2020-12-09 16:50 UTC
