### ISSUE TITLE
PXE Boot of Tumbleweed iso fails with network setup failure when booting

### ISSUE THREAD

**Issue by JulianBane** [OSInside/kiwi#1802] opened 2021-04-27 14:17 UTC
## Problem description
I have followed this document to setup a PXE Boot of an exported Tunmbleweed Live CD .iso
https://forums.opensuse.org/showthread.php/521017-Pxe-boot-sever-in-combination-with-Kiwi-Image-System

## Expected behaviour
I expected it to boot normally but it actually fails with a network failure. The startup log shows:
`[ 16.429139] dracut: FATAL: Network setup failed, see tmp/net.info`
and /tmp/net.info is:
`/lib/kiwi-lib.sh: line 78: ifup: command not found`

The full transcript of what I did and some very helpful comments are in an openSUSE forum thread that I started here - the thread is actually very short:

https://forums.opensuse.org/showthread.php/553245-PXE-boot-of-an-ISO-live-distrbution

Please see comment #5 from @arvidjaar as he clearly knows way more than I do on this. 

## Steps to reproduce the behaviour
See above link. I also have a preserved system and happy to test potential fixes,

## OS and Software information
+ KIWI version: unknown
+ Operating system: openSUSE Tumbleweed iso
https://download.opensuse.org/tumbleweed/iso/openSUSE-Tumbleweed-XFCE-Live-x86_64-Current.iso.mirrorlist
Downloaded on 26-04-2021
+ OBS version: 

I have add a link to issue #1684 as it maybe related.

**Comment by schaefi** [comment] 2021-04-28 13:35
Pretty much a duplicate of #1684

**Comment by arvidjaar** [comment] 2021-04-28 14:02
It probably depends on what "was not functional" means. If it means - kiwi does not expect `network-wicked` - that's correct. If it means "`network-wicked` failed to bring up network" - I have no evidence of it. The problem is that even if `network-wicked` correctly initialized network, kiwi-live does not understand it and insists on having `network-legacy`.

So I am not convinced it is duplicate.

**Comment by arvidjaar** [comment] 2021-05-11 13:39
> Thus we need to adapt our code to support the "other" way of checking if the network is up.

Why it needs to check it? It already waits for required device and device will appear when network is up. Now may be it needs to **configure** network, but that can be done differently as e.g. kiwi-overlay module shows:

```
if [ "${need_network}" = "1" ];then
    echo "rd.neednet=1" > /etc/cmdline.d/kiwi-generated.conf
    if ! getarg "ip="; then
        echo "ip=dhcp" >> /etc/cmdline.d/kiwi-generated.conf
    fi
```

wicked scripts will parse command line and create suitable configuration for `ip=dhcp`. It should be compatible with both legacy and wicked.

**Comment by schaefi** [comment] 2021-05-11 14:21
yes sorry I did not made that clear. The code in question does:

```
elif ! ifup lan0 &>/tmp/net.info;then
            die "Network setup failed, see /tmp/net.info"
        fi
```

and this needs to change to do it generically correct like you saw it in other parts of the dracut code

```
echo "rd.neednet=1" > /etc/cmdline.d/kiwi-generated.conf
if ! getarg "ip="; then
    echo "ip=dhcp" >> /etc/cmdline.d/kiwi-generated.conf
fi
```

> It should be compatible with both legacy and wicked.

yes

Thanks we will do it that way

**Comment by JulianBane** [comment] 2021-05-12 07:26
I still have my original setup in place if you would like someone to test a newly generated ISO

**Comment by schaefi** [comment] 2021-05-12 07:55
Thanks, I'm going to fix this issue in the next days. If you could give the fix a test this would be awesome

**Comment by schaefi** [comment] 2021-05-12 09:37
@JulianBane I've created a pull request which I think fixes the defect. Could you give it a test in your environment ?
Thanks much

**Comment by JulianBane** [comment] 2021-05-12 15:11
@schaefi OK, I am bit lost here but I need someone to build an openSUSE ISO for me to test as I have no means or don't know how to build one. Ideally it will be "openSUSE-Tumbleweed-XFCE-Live-x86_64"

@arvidjaar might you be able to help?

Sorry, but I am out of my depth here!

**Comment by arvidjaar** [comment] 2021-05-12 16:46
> @arvidjaar might you be able to help?

You could try http://download.opensuse.org/repositories/home:/arvidjaar:/branches:/openSUSE:/Factory:/Live/images/iso/openSUSE-Tumbleweed-XFCE-Live-x86_64-Build193.2-Media.iso

I do not get GUI, but it is probably something with my VM. It boots otherwise (locally from CD). I verified that initrd contains patched module.

**Comment by arvidjaar** [comment] 2021-05-12 17:15
> probably something with my VM

Yes, Live CD does not like virgl; disabling it boots into GUI. So it is entirely unrelated to this issue.

**Comment by JulianBane** [comment] 2021-05-12 17:36
OK, I'll test it tomorrow, didn't realize it had already been built.

**Comment by JulianBane** [comment] 2021-05-13 07:26
It's not working for me. The VM that I am booting over the net is reporting that it can't mount the ISO. 

I am moving the tread back to the openSUSE thread I mentioned in the start of this thread as I suspect it's more relevant there than here.

**Comment by arvidjaar** [comment] 2021-05-13 07:40
@JulianBane 

> It's not working for me.

Now you may actually be hitting https://bugzilla.opensuse.org/show_bug.cgi?id=1182227. Try workarounds suggested there (like adding explicit interface name, `ip=eth0:dhcp`, to kernel command line; replace `eth0` with your actual interface name).

**Comment by arvidjaar** [comment] 2021-05-14 17:04
@JulianBane 

Please test updated image which includes updated patch. It works for me. If you have single LAN interface it should work with `rd.kiwi.live.pxe root=live:AOEINTERFACE=e1.0 ip=lan0:none`, otherwise omit `rd.kiwi.live.pxe` and replace `lan0` with actual interface name you intend to use.

Image is in the same directory just build number is incremented. I do not put direct link as image gets rebuild automatically so link may become outdated.

**Comment by JulianBane** [comment] 2021-05-14 18:34
@ Andrei Borzenkov

Extracted initrd and linux files from new ISO, openSUSE-Tumbleweed-XFCE-Live-x86_64-Build193.5-Media.iso

Relevant PXE line is now:
append initrd=tumbleweed/initrd ip=lan0:none rd.kiwi.live.pxe root=live:AOEINTERFACE=e0.1 rd.shell

But fails to boot. It hangs at this point:-

![Screenshot 2021-05-14 191715](https://user-images.githubusercontent.com/20241513/118312298-08072e00-b4e9-11eb-9671-d35fe824062e.gif)

Then dracut issues repeated timeouts.

When it finally drops into maintenance shell, the network is up and running but only has ipV6 addresses, no ipV4 address has been assigned.

Booting with PXE line of:
append initrd=tumbleweed/initrd ip=lan0:dhcp rd.kiwi.live.pxe root=live:AOEINTERFACE=e0.1 rd.shell

Is similar but lan0 now has an ipV4 address too.

**Comment by arvidjaar** [comment] 2021-05-14 19:58
AoE requires direct L2 connectivity. IP addresses are not used at all. AoE server and your system must be connected to the same switch/bridge.

**Comment by arvidjaar** [comment] 2021-05-14 20:07
> AoE requires direct L2 connectivity. 

Do you see any AoE traffic on AoE server with packet sniffer?

**Comment by arvidjaar** [comment] 2021-05-15 05:40
> It hangs at this point:

Hmm ... at this point I get additional kernel output `lan0: link becomes ready`. It seems that something delays network initialization. Providing full rdsosreport.txt may give some hint.

I do get pause at this point, it is likely due to `aoe` being loaded early, before network is up, so we wait until next detection cycle.

**Comment by JulianBane** [comment] 2021-05-15 07:28
Hmmmm!!!

OK, I ran up the systems this morning, just like last night. It hung (paused) at the same point but when it continued, instead of giving a lot of time out messages it continued to a working system.This was with a PXE line of:
append initrd=tumbleweed/initrd ip=lan0:dhcp rd.kiwi.live.pxe root=live:AOEINTERFACE=e0.1 rd.shell

The lines in the journal at the pause are as follows (full journal available at: https://drive.google.com/file/d/1Mntq6JPvCe-BrNE5AW_-ySQYcT3ZSgbG/view?usp=sharing): 

```
May 15 03:03:34 localhost kernel: [drm] Atomic: yes.

May 15 03:03:34 localhost kernel: [drm:vmw_host_log [vmwgfx]] *ERROR* Failed to send host log message.

May 15 03:03:34 localhost kernel: [drm:vmw_host_log [vmwgfx]] *ERROR* Failed to send host log message.

May 15 03:03:34 localhost kernel: fbcon: svgadrmfb (fb0) is primary device

May 15 03:03:34 localhost kernel: Console: switching to colour frame buffer device 100x37

May 15 03:03:34 localhost kernel: [drm] Initialized vmwgfx 2.18.0 20200114 for 0000:00:02.0 on minor 0

May 15 03:03:34 localhost systemd[1]: Finished Wait for udev To Complete Device Initialization.

May 15 03:03:34 localhost systemd[1]: Reached target System Initialization.

May 15 03:03:34 localhost systemd[1]: Reached target Basic System.

May 15 03:03:35 localhost wickedd-dhcp4[390]: lan0: Committed DHCPv4 lease with address 192.168.25.137 (lease time 86400 sec, renew in 43200 sec, rebind in 75600 sec)

May 15 03:03:35 localhost wickedd[392]: disabling generic batch updater action 'netconfig batch': test failure, update to sysconfig-netconfig >= 0.84

May 15 03:04:02 localhost kernel: aoe: e0.1: setting 1024 byte data frames

May 15 03:04:02 localhost kernel: aoe: 080027ac269e e0.1 v4018 has 1888256 sectors

May 15 03:04:02 localhost kernel:  etherd/e0.1: p1 p2

May 15 03:04:02 localhost dracut-initqueue[990]: kiwi_align='1048576'

May 15 03:04:02 localhost dracut-initqueue[990]: kiwi_boot_timeout=''


```
A PXE line of:
append initrd=tumbleweed/initrd ip=lan0:none rd.kiwi.live.pxe root=live:AOEINTERFACE=e0.1 rd.shell

also boots correctly but has no ipV4 IP address. No idea why it did not work last night.

**Comment by JulianBane** [comment] 2021-05-15 08:21
I have also tested the diskless VM (VirtualBox) with the emulated network card set to both "Intel PRO/1000 MT Desktop (82540EM)" and "PCnet-PCI II (Am79C970A)". They now both boot fine.

**Closed** 2021-05-17 12:22 UTC
Labels: P1
